# flake8: noqa — word bank + pronunciations for flashcards/words-embed.js
# Regenerate embed: python3 flashcards/tools/build_words_embed.py
# Refresh IPA in embed from this map: python3 flashcards/tools/merge-pronunciations.py

PRON = {
    "cat": ("/kæt/", "KAT"),
    "dog": ("/dɔːɡ/", "DAWG"),
    "sun": ("/sʌn/", "SUN"),
    "bed": ("/bɛd/", "BED"),
    "pen": ("/pɛn/", "PEN"),
    "cup": ("/kʌp/", "KUP"),
    "map": ("/mæp/", "MAP"),
    "hat": ("/hæt/", "HAT"),
    "pig": ("/pɪɡ/", "PIG"),
    "bat": ("/bæt/", "BAT"),
    "bus": ("/bʌs/", "BUS"),
    "red": ("/rɛd/", "RED"),
    "run": ("/rʌn/", "RUN"),
    "sit": ("/sɪt/", "SIT"),
    "top": ("/tɑːp/", "TAHP"),
    "hot": ("/hɑːt/", "HAHT"),
    "big": ("/bɪɡ/", "BIG"),
    "bag": ("/bæɡ/", "BAG"),
    "leg": ("/lɛɡ/", "LEG"),
    "man": ("/mæn/", "MAN"),
    "fan": ("/fæn/", "FAN"),
    "pan": ("/pæn/", "PAN"),
    "cap": ("/kæp/", "KAP"),
    "net": ("/nɛt/", "NET"),
    "jet": ("/dʒɛt/", "JET"),
    "log": ("/lɔːɡ/", "LAWG"),
    "van": ("/væn/", "VAN"),
    "web": ("/wɛb/", "WEB"),
    "wig": ("/wɪɡ/", "WIG"),
    "zip": ("/zɪp/", "ZIP"),
    "box": ("/bɑːks/", "BAHKS"),
    "fox": ("/fɑːks/", "FAHKS"),
    "six": ("/sɪks/", "SIKS"),
    "rug": ("/rʌɡ/", "RUG"),
    "tug": ("/tʌɡ/", "TUG"),
    "mug": ("/mʌɡ/", "MUG"),
    "bun": ("/bʌn/", "BUN"),
    "fun": ("/fʌn/", "FUN"),
    "hen": ("/hɛn/", "HEN"),
    "cob": ("/kɑːb/", "KAHB"),
    "flag": ("/flæɡ/", "FLAG"),
    "plug": ("/plʌɡ/", "PLUG"),
    "drum": ("/drʌm/", "DRUM"),
    "frog": ("/frɔːɡ/", "FRAHG"),
    "plan": ("/plæn/", "PLAN"),
    "block": ("/blɑːk/", "BLAHK"),
    "club": ("/klʌb/", "KLUB"),
    "crop": ("/krɑːp/", "KRAHP"),
    "star": ("/stɑːr/", "STAR"),
    "stop": ("/stɑːp/", "STOP"),
    "swim": ("/swɪm/", "SWIM"),
    "sled": ("/slɛd/", "SLED"),
    "trim": ("/trɪm/", "TRIM"),
    "trap": ("/træp/", "TRAP"),
    "crib": ("/krɪb/", "KRIB"),
    "grab": ("/ɡræb/", "GRAB"),
    "glad": ("/ɡlæd/", "GLAD"),
    "flip": ("/flɪp/", "FLIP"),
    "clip": ("/klɪp/", "KLIP"),
    "drop": ("/drɑːp/", "DRAHP"),
    "ship": ("/ʃɪp/", "SHIP"),
    "chip": ("/tʃɪp/", "CHIP"),
    "fish": ("/fɪʃ/", "FISH"),
    "shoe": ("/ʃuː/", "SHOO"),
    "chat": ("/tʃæt/", "CHAT"),
    "shop": ("/ʃɑːp/", "SHOP"),
    "shell": ("/ʃɛl/", "SHEL"),
    "dish": ("/dɪʃ/", "DISH"),
    "wish": ("/wɪʃ/", "WISH"),
    "chop": ("/tʃɑːp/", "CHOP"),
    "chin": ("/tʃɪn/", "CHIN"),
    "math": ("/mæθ/", "MATH"),
    "path": ("/pæθ/", "PATH"),
    "bath": ("/bæθ/", "BATH"),
    "moth": ("/mɔːθ/", "MAWTH"),
    "thin": ("/θɪn/", "THIN"),
    "that": ("/ðæt/", "THAT"),
    "then": ("/ðɛn/", "THEN"),
    "when": ("/wɛn/", "WEN"),
    "white": ("/waɪt/", "WYTE"),
    "whale": ("/weɪl/", "WAYL"),
    "the": ("/ðə/", "thuh"),
    "and": ("/ænd/", "AND"),
    "you": ("/juː/", "YOO"),
    "is": ("/ɪz/", "IZ"),
    "it": ("/ɪt/", "IT"),
    "in": ("/ɪn/", "IN"),
    "on": ("/ɑːn/", "ON"),
    "to": ("/tuː/", "TOO"),
    "we": ("/wiː/", "WEE"),
    "go": ("/ɡoʊ/", "GOH"),
    "me": ("/miː/", "MEE"),
    "at": ("/æt/", "AT"),
    "they": ("/ðeɪ/", "THAY"),
    "have": ("/hæv/", "HAV"),
    "said": ("/sɛd/", "SED"),
    "from": ("/frʌm/", "FRUM"),
    "what": ("/wʌt/", "WUT"),
    "where": ("/wer/", "WAIR"),
    "why": ("/waɪ/", "WY"),
    "how": ("/haʊ/", "HOW"),
    "could": ("/kʊd/", "KOOD"),
    "was": ("/wʌz/", "WUZ"),
    "are": ("/ɑːr/", "AR"),
    "now": ("/naʊ/", "NOW"),
    "she": ("/ʃiː/", "SHE"),
    "apple": ("/ˈæpəl/", "AP-ul"),
    "banana": ("/bəˈnænə/", "buh-NAN-uh"),
    "ball": ("/bɔːl/", "BAWL"),
    "tree": ("/triː/", "TREE"),
    "bird": ("/bɜːrd/", "BURD"),
    "water": ("/ˈwɔːtər/", "WAW-ter"),
    "milk": ("/mɪlk/", "MILK"),
    "book": ("/bʊk/", "BOOK"),
    "door": ("/dɔːr/", "DOR"),
    "house": ("/haʊs/", "HOWSS"),
    "school": ("/skuːl/", "SKOOL"),
    "teacher": ("/ˈtiːtʃər/", "TEE-chur"),
    "friend": ("/frɛnd/", "FREND"),
    "family": ("/ˈfæməli/", "FAM-uh-lee"),
    "play": ("/pleɪ/", "PLAY"),
    # K / Gr 1 extensions (heart words + early CVC)
    "a": ("/ə/", "uh"),
    "see": ("/siː/", "SEE"),
    "my": ("/maɪ/", "MY"),
    "can": ("/kæn/", "KAN"),
    "look": ("/lʊk/", "LOOK"),
    "like": ("/laɪk/", "LYKE"),
    "here": ("/hɪər/", "HEER"),
    "come": ("/kʌm/", "KUM"),
    "one": ("/wʌn/", "WUN"),
    "two": ("/tuː/", "TOO"),
    "three": ("/θriː/", "THREE"),
    "up": ("/ʌp/", "UP"),
    "down": ("/daʊn/", "DOWN"),
    "yes": ("/jɛs/", "YES"),
    "no": ("/noʊ/", "NOH"),
    "help": ("/hɛlp/", "HELP"),
    "jump": ("/dʒʌmp/", "JUMP"),
    "he": ("/hiː/", "HEE"),
    "his": ("/hɪz/", "HIZ"),
    "her": ("/hɜːr/", "HUR"),
    "at": ("/æt/", "AT"),
    "for": ("/fɔːr/", "FOR"),
    "get": ("/ɡɛt/", "GET"),
    "not": ("/nɑːt/", "NOT"),
    "so": ("/soʊ/", "SOH"),
    "day": ("/deɪ/", "DAY"),
    "want": ("/wɑːnt/", "WAHNT"),
    "this": ("/ðɪs/", "THIS"),
    "good": ("/ɡʊd/", "GOOD"),
    "all": ("/ɔːl/", "AWL"),
    "out": ("/aʊt/", "OUT"),
    "make": ("/meɪk/", "MAYK"),
    "say": ("/seɪ/", "SAY"),
    "your": ("/jʊər/", "YOOR"),
    "funny": ("/ˈfʌni/", "FUN-ee"),
    "little": ("/ˈlɪtəl/", "LIT-ul"),
    "some": ("/sʌm/", "SUM"),
    "there": ("/ðɛr/", "THAIR"),
    "an": ("/æn/", "AN"),
    "him": ("/hɪm/", "HIM"),
    "has": ("/hæz/", "HAZ"),
    "had": ("/hæd/", "HAD"),
    "were": ("/wɜːr/", "WUR"),
    "into": ("/ˈɪntuː/", "IN-too"),
    "off": ("/ɔːf/", "AWF"),
    "our": ("/aʊər/", "OW-er"),
    "ask": ("/æsk/", "ASK"),
    "dad": ("/dæd/", "DAD"),
    "mom": ("/mɑːm/", "MAHM"),
    "car": ("/kɑːr/", "KAR"),
    "ant": ("/ænt/", "ANT"),
    "tub": ("/tʌb/", "TUB"),
    "hug": ("/hʌɡ/", "HUG"),
    "pet": ("/pɛt/", "PET"),
    "jam": ("/dʒæm/", "JAM"),
}


def _r(
    word: str,
    emoji: str,
    chinese: str,
    type_: str,
    difficulty: int,
    word_type: str,
    grade: str,
) -> dict:
    return {
        "word": word,
        "emoji": emoji,
        "chinese": chinese,
        "type": type_,
        "difficulty": difficulty,
        "wordType": word_type,
        "gradeLevel": grade,
    }


# 40 CVC · K
_CVC = [
    ("cat", "🐱", "猫"),
    ("dog", "🐶", "狗"),
    ("sun", "☀️", "太阳"),
    ("bed", "🛏️", "床"),
    ("pen", "✏️", "笔"),
    ("cup", "🥤", "杯子"),
    ("map", "🗺️", "地图"),
    ("hat", "🎩", "帽子"),
    ("pig", "🐷", "猪"),
    ("bat", "🏏", "球棒"),
    ("bus", "🚌", "巴士"),
    ("red", "🔴", "红色"),
    ("run", "🏃", "跑"),
    ("sit", "🧘", "坐"),
    ("top", "🔝", "顶"),
    ("hot", "🌶️", "热"),
    ("big", "⬆️", "大"),
    ("bag", "👜", "包"),
    ("leg", "🦵", "腿"),
    ("man", "👨", "男人"),
    ("fan", "🪭", "扇子"),
    ("pan", "🍳", "平底锅"),
    ("cap", "🧢", "鸭舌帽"),
    ("net", "🥅", "网"),
    ("jet", "✈️", "喷气机"),
    ("log", "🪵", "原木"),
    ("van", "🚐", "货车"),
    ("web", "🕸️", "网"),
    ("wig", "💇", "假发"),
    ("zip", "🤐", "拉链"),
    ("box", "📦", "盒子"),
    ("fox", "🦊", "狐狸"),
    ("six", "6️⃣", "六"),
    ("rug", "🟫", "地毯"),
    ("tug", "🪢", "拽"),
    ("mug", "☕", "马克杯"),
    ("bun", "🥯", "小面包"),
    ("fun", "🎉", "好玩"),
    ("hen", "🐔", "母鸡"),
    ("cob", "🌽", "玉米棒"),
    ("dad", "👨", "爸爸"),
    ("mom", "👩", "妈妈"),
    ("car", "🚗", "汽车"),
    ("ant", "🐜", "蚂蚁"),
    ("tub", "🛁", "浴缸"),
    ("hug", "🤗", "抱"),
    ("pet", "🐾", "宠物"),
    ("jam", "🍓", "果酱"),
]

# 20 blends · Gr 1
_BLEND = [
    ("flag", "🚩", "旗"),
    ("plug", "🔌", "塞子"),
    ("drum", "🥁", "鼓"),
    ("frog", "🐸", "青蛙"),
    ("plan", "📋", "计划"),
    ("block", "🧱", "积木"),
    ("club", "♣️", "俱乐部"),
    ("crop", "🌾", "庄稼"),
    ("star", "⭐", "星星"),
    ("stop", "🛑", "停"),
    ("swim", "🏊", "游泳"),
    ("sled", "🛷", "雪橇"),
    ("trim", "✂️", "修剪"),
    ("trap", "🪤", "陷阱"),
    ("crib", "🛏️", "婴儿床"),
    ("grab", "✊", "抓"),
    ("glad", "😊", "高兴"),
    ("flip", "🤸", "翻"),
    ("clip", "📎", "夹子"),
    ("drop", "💧", "滴"),
]

# 20 digraphs · Gr 1
_DIGRAPH = [
    ("ship", "🚢", "船"),
    ("chip", "🥔", "薯片"),
    ("fish", "🐟", "鱼"),
    ("shoe", "👟", "鞋"),
    ("chat", "💬", "聊天"),
    ("shop", "🛒", "商店"),
    ("shell", "🐚", "贝壳"),
    ("dish", "🍽️", "盘子"),
    ("wish", "🌠", "愿望"),
    ("chop", "🔪", "砍"),
    ("chin", "🙂", "下巴"),
    ("math", "➕", "数学"),
    ("path", "🛤️", "小路"),
    ("bath", "🛁", "洗澡"),
    ("moth", "🦋", "蛾"),
    ("thin", "📏", "薄"),
    ("that", "👉", "那"),
    ("then", "⏭️", "然后"),
    ("white", "⚪", "白色"),
    ("whale", "🐋", "鲸"),
]

# 25 Heart words · 11 K + 14 Gr 1
_SIGHT_K = [
    ("the", "✨", "这；那个"),
    ("and", "➕", "和"),
    ("you", "🫵", "你"),
    ("is", "ℹ️", "是"),
    ("it", "📌", "它"),
    ("in", "📥", "在…里"),
    ("on", "📍", "在…上"),
    ("to", "➡️", "向；到"),
    ("we", "🧑‍🤝‍🧑", "我们"),
    ("go", "🚶", "去"),
    ("me", "🙋", "我"),
    ("a", "🔤", "一个（冠词）"),
    ("see", "👀", "看见"),
    ("my", "🧒", "我的"),
    ("can", "💪", "能"),
    ("look", "👀", "看"),
    ("like", "👍", "喜欢"),
    ("here", "📍", "这里"),
    ("come", "🚶‍➡️", "来"),
    ("one", "1️⃣", "一"),
    ("two", "2️⃣", "二"),
    ("three", "3️⃣", "三"),
    ("up", "⬆️", "上"),
    ("down", "⬇️", "下"),
    ("yes", "✅", "是"),
    ("no", "❎", "不"),
    ("help", "🆘", "帮助"),
    ("jump", "🦘", "跳"),
    ("he", "👦", "他"),
    ("his", "🏷️", "他的"),
    ("her", "👧", "她；她的"),
    ("at", "🎯", "在"),
    ("for", "🎁", "为了"),
    ("get", "🤲", "得到"),
    ("not", "🚫", "不"),
    ("so", "✨", "所以；很"),
    ("day", "🌤️", "天；日子"),
    ("want", "🙏", "想要"),
    ("this", "👆", "这个"),
    ("good", "👍", "好"),
    ("all", "🔁", "全部"),
    ("out", "🚪", "外；出"),
    ("make", "🛠️", "做"),
    ("say", "💬", "说"),
    ("your", "👉", "你的"),
    ("funny", "😂", "好笑"),
    ("little", "🤏", "小"),
]
_SIGHT_1 = [
    ("they", "👥", "他们"),
    ("have", "📦", "有"),
    ("said", "💬", "说"),
    ("from", "📤", "从"),
    ("what", "❓", "什么"),
    ("when", "🕐", "何时"),
    ("where", "🧭", "哪里"),
    ("why", "🤔", "为什么"),
    ("how", "❔", "怎样"),
    ("could", "🔮", "能"),
    ("was", "⏪", "是"),
    ("are", "↔️", "是"),
    ("now", "📍", "现在"),
    ("she", "👩", "她"),
    ("some", "🤲", "一些"),
    ("there", "👉", "那里"),
    ("an", "📝", "一个"),
    ("him", "👦", "他（宾格）"),
    ("has", "📦", "有（三单）"),
    ("had", "📜", "有过"),
    ("were", "👥", "是（are 的过去）"),
    ("into", "📥", "进入"),
    ("off", "⏹️", "离开；关掉"),
    ("our", "🧑‍🤝‍🧑", "我们的"),
    ("ask", "🙋", "问"),
]

# 15 basic vocabulary
_BASIC = [
    ("apple", "🍎", "苹果", 2, "K"),
    ("banana", "🍌", "香蕉", 3, "1"),
    ("ball", "⚽", "球", 2, "K"),
    ("tree", "🌳", "树", 2, "K"),
    ("bird", "🐦", "鸟", 2, "K"),
    ("water", "💧", "水", 2, "K"),
    ("milk", "🥛", "牛奶", 2, "K"),
    ("book", "📚", "书", 2, "K"),
    ("door", "🚪", "门", 2, "K"),
    ("house", "🏠", "房子", 3, "1"),
    ("school", "🏫", "学校", 3, "1"),
    ("teacher", "👩‍🏫", "老师", 3, "1"),
    ("friend", "🤝", "朋友", 3, "1"),
    ("family", "👪", "家庭", 3, "1"),
    ("play", "🎮", "玩", 2, "K"),
]


def build_base_rows():
    rows = []
    for w, e, zh in _CVC:
        rows.append(_r(w, e, zh, "cvc", 2, "CVC", "K"))
    for w, e, zh in _BLEND:
        rows.append(_r(w, e, zh, "phonics", 4, "Blend", "1"))
    for w, e, zh in _DIGRAPH:
        rows.append(_r(w, e, zh, "phonics", 4, "Digraph", "1"))
    for w, e, zh in _SIGHT_K:
        rows.append(_r(w, e, zh, "sight", 2, "Heart word", "K"))
    for w, e, zh in _SIGHT_1:
        rows.append(_r(w, e, zh, "sight", 3, "Heart word", "1"))
    for w, e, zh, d, g in _BASIC:
        rows.append(_r(w, e, zh, "basic", d, "Basic", g))
    return rows


BASE_ROWS = build_base_rows()
