# flake8: noqa — word bank + pronunciations for flashcards/words-embed.js
# Regenerate embed: python3 flashcards/tools/build_words_embed.py
# Refresh IPA in embed from this map: python3 flashcards/tools/merge-pronunciations.py

PRON = {
    "cat": ("/kæt/", "KAT"),
    "dog": ("/dɔːɡ/", "DAWG"),
    "sun": ("/sʌn/", "SUN"),
    "bed": ("/bɛd/", "BED"),
    "pen": ("/pɛn/", "PEN"),
    "cup": ("/kʌp/", "KUP"),
    "map": ("/mæp/", "MAP"),
    "hat": ("/hæt/", "HAT"),
    "pig": ("/pɪɡ/", "PIG"),
    "bat": ("/bæt/", "BAT"),
    "bus": ("/bʌs/", "BUS"),
    "red": ("/rɛd/", "RED"),
    "run": ("/rʌn/", "RUN"),
    "sit": ("/sɪt/", "SIT"),
    "top": ("/tɑːp/", "TAHP"),
    "hot": ("/hɑːt/", "HAHT"),
    "big": ("/bɪɡ/", "BIG"),
    "bag": ("/bæɡ/", "BAG"),
    "leg": ("/lɛɡ/", "LEG"),
    "man": ("/mæn/", "MAN"),
    "fan": ("/fæn/", "FAN"),
    "pan": ("/pæn/", "PAN"),
    "cap": ("/kæp/", "KAP"),
    "net": ("/nɛt/", "NET"),
    "jet": ("/dʒɛt/", "JET"),
    "log": ("/lɔːɡ/", "LAWG"),
    "van": ("/væn/", "VAN"),
    "web": ("/wɛb/", "WEB"),
    "wig": ("/wɪɡ/", "WIG"),
    "zip": ("/zɪp/", "ZIP"),
    "box": ("/bɑːks/", "BAHKS"),
    "fox": ("/fɑːks/", "FAHKS"),
    "six": ("/sɪks/", "SIKS"),
    "rug": ("/rʌɡ/", "RUG"),
    "tug": ("/tʌɡ/", "TUG"),
    "mug": ("/mʌɡ/", "MUG"),
    "bun": ("/bʌn/", "BUN"),
    "fun": ("/fʌn/", "FUN"),
    "hen": ("/hɛn/", "HEN"),
    "cob": ("/kɑːb/", "KAHB"),
    "flag": ("/flæɡ/", "FLAG"),
    "plug": ("/plʌɡ/", "PLUG"),
    "drum": ("/drʌm/", "DRUM"),
    "frog": ("/frɔːɡ/", "FRAHG"),
    "plan": ("/plæn/", "PLAN"),
    "block": ("/blɑːk/", "BLAHK"),
    "club": ("/klʌb/", "KLUB"),
    "crop": ("/krɑːp/", "KRAHP"),
    "star": ("/stɑːr/", "STAR"),
    "stop": ("/stɑːp/", "STOP"),
    "swim": ("/swɪm/", "SWIM"),
    "sled": ("/slɛd/", "SLED"),
    "trim": ("/trɪm/", "TRIM"),
    "trap": ("/træp/", "TRAP"),
    "crib": ("/krɪb/", "KRIB"),
    "grab": ("/ɡræb/", "GRAB"),
    "glad": ("/ɡlæd/", "GLAD"),
    "flip": ("/flɪp/", "FLIP"),
    "clip": ("/klɪp/", "KLIP"),
    "drop": ("/drɑːp/", "DRAHP"),
    "ship": ("/ʃɪp/", "SHIP"),
    "chip": ("/tʃɪp/", "CHIP"),
    "fish": ("/fɪʃ/", "FISH"),
    "shoe": ("/ʃuː/", "SHOO"),
    "chat": ("/tʃæt/", "CHAT"),
    "shop": ("/ʃɑːp/", "SHOP"),
    "shell": ("/ʃɛl/", "SHEL"),
    "dish": ("/dɪʃ/", "DISH"),
    "wish": ("/wɪʃ/", "WISH"),
    "chop": ("/tʃɑːp/", "CHOP"),
    "chin": ("/tʃɪn/", "CHIN"),
    "math": ("/mæθ/", "MATH"),
    "path": ("/pæθ/", "PATH"),
    "bath": ("/bæθ/", "BATH"),
    "moth": ("/mɔːθ/", "MAWTH"),
    "thin": ("/θɪn/", "THIN"),
    "that": ("/ðæt/", "THAT"),
    "then": ("/ðɛn/", "THEN"),
    "when": ("/wɛn/", "WEN"),
    "white": ("/waɪt/", "WYTE"),
    "whale": ("/weɪl/", "WAYL"),
    "the": ("/ðə/", "thuh"),
    "and": ("/ænd/", "AND"),
    "you": ("/juː/", "YOO"),
    "is": ("/ɪz/", "IZ"),
    "it": ("/ɪt/", "IT"),
    "in": ("/ɪn/", "IN"),
    "on": ("/ɑːn/", "ON"),
    "to": ("/tuː/", "TOO"),
    "we": ("/wiː/", "WEE"),
    "go": ("/ɡoʊ/", "GOH"),
    "me": ("/miː/", "MEE"),
    "at": ("/æt/", "AT"),
    "they": ("/ðeɪ/", "THAY"),
    "have": ("/hæv/", "HAV"),
    "said": ("/sɛd/", "SED"),
    "from": ("/frʌm/", "FRUM"),
    "what": ("/wʌt/", "WUT"),
    "where": ("/wer/", "WAIR"),
    "why": ("/waɪ/", "WY"),
    "how": ("/haʊ/", "HOW"),
    "could": ("/kʊd/", "KOOD"),
    "was": ("/wʌz/", "WUZ"),
    "are": ("/ɑːr/", "AR"),
    "now": ("/naʊ/", "NOW"),
    "she": ("/ʃiː/", "SHE"),
    "apple": ("/ˈæpəl/", "AP-ul"),
    "banana": ("/bəˈnænə/", "buh-NAN-uh"),
    "ball": ("/bɔːl/", "BAWL"),
    "tree": ("/triː/", "TREE"),
    "bird": ("/bɜːrd/", "BURD"),
    "water": ("/ˈwɔːtər/", "WAW-ter"),
    "milk": ("/mɪlk/", "MILK"),
    "book": ("/bʊk/", "BOOK"),
    "door": ("/dɔːr/", "DOR"),
    "house": ("/haʊs/", "HOWSS"),
    "school": ("/skuːl/", "SKOOL"),
    "teacher": ("/ˈtiːtʃər/", "TEE-chur"),
    "friend": ("/frɛnd/", "FREND"),
    "family": ("/ˈfæməli/", "FAM-uh-lee"),
    "play": ("/pleɪ/", "PLAY"),
    # K / Gr 1 extensions (heart words + early CVC)
    "a": ("/ə/", "uh"),
    "see": ("/siː/", "SEE"),
    "my": ("/maɪ/", "MY"),
    "can": ("/kæn/", "KAN"),
    "look": ("/lʊk/", "LOOK"),
    "like": ("/laɪk/", "LYKE"),
    "here": ("/hɪər/", "HEER"),
    "come": ("/kʌm/", "KUM"),
    "one": ("/wʌn/", "WUN"),
    "two": ("/tuː/", "TOO"),
    "three": ("/θriː/", "THREE"),
    "up": ("/ʌp/", "UP"),
    "down": ("/daʊn/", "DOWN"),
    "yes": ("/jɛs/", "YES"),
    "no": ("/noʊ/", "NOH"),
    "help": ("/hɛlp/", "HELP"),
    "jump": ("/dʒʌmp/", "JUMP"),
    "he": ("/hiː/", "HEE"),
    "his": ("/hɪz/", "HIZ"),
    "her": ("/hɜːr/", "HUR"),
    "for": ("/fɔːr/", "FOR"),
    "get": ("/ɡɛt/", "GET"),
    "not": ("/nɑːt/", "NOT"),
    "so": ("/soʊ/", "SOH"),
    "day": ("/deɪ/", "DAY"),
    "want": ("/wɑːnt/", "WAHNT"),
    "this": ("/ðɪs/", "THIS"),
    "good": ("/ɡʊd/", "GOOD"),
    "all": ("/ɔːl/", "AWL"),
    "out": ("/aʊt/", "OUT"),
    "make": ("/meɪk/", "MAYK"),
    "say": ("/seɪ/", "SAY"),
    "your": ("/jʊər/", "YOOR"),
    "funny": ("/ˈfʌni/", "FUN-ee"),
    "little": ("/ˈlɪtəl/", "LIT-ul"),
    "some": ("/sʌm/", "SUM"),
    "there": ("/ðɛr/", "THAIR"),
    "an": ("/æn/", "AN"),
    "him": ("/hɪm/", "HIM"),
    "has": ("/hæz/", "HAZ"),
    "had": ("/hæd/", "HAD"),
    "were": ("/wɜːr/", "WUR"),
    "into": ("/ˈɪntuː/", "IN-too"),
    "off": ("/ɔːf/", "AWF"),
    "our": ("/aʊər/", "OW-er"),
    "ask": ("/æsk/", "ASK"),
    "dad": ("/dæd/", "DAD"),
    "mom": ("/mɑːm/", "MAHM"),
    "car": ("/kɑːr/", "KAR"),
    "ant": ("/ænt/", "ANT"),
    "tub": ("/tʌb/", "TUB"),
    "hug": ("/hʌɡ/", "HUG"),
    "pet": ("/pɛt/", "PET"),
    "jam": ("/dʒæm/", "JAM"),
    # Expanded CVC
    "mat": ("/mæt/", "MAT"),
    "sat": ("/sæt/", "SAT"),
    "rat": ("/ræt/", "RAT"),
    "fat": ("/fæt/", "FAT"),
    "pat": ("/pæt/", "PAT"),
    "wag": ("/wæɡ/", "WAG"),
    "tag": ("/tæɡ/", "TAG"),
    "ham": ("/hæm/", "HAM"),
    "ram": ("/ræm/", "RAM"),
    "tab": ("/tæb/", "TAB"),
    "sad": ("/sæd/", "SAD"),
    "mad": ("/mæd/", "MAD"),
    "pad": ("/pæd/", "PAD"),
    "lap": ("/læp/", "LAP"),
    "tap": ("/tæp/", "TAP"),
    "nap": ("/næp/", "NAP"),
    "gap": ("/ɡæp/", "GAP"),
    "sap": ("/sæp/", "SAP"),
    "yak": ("/jæk/", "YAK"),
    "vat": ("/væt/", "VAT"),
    "bet": ("/bɛt/", "BET"),
    "let": ("/lɛt/", "LET"),
    "ten": ("/tɛn/", "TEN"),
    "men": ("/mɛn/", "MEN"),
    "wet": ("/wɛt/", "WET"),
    "set": ("/sɛt/", "SET"),
    "met": ("/mɛt/", "MET"),
    "vet": ("/vɛt/", "VET"),
    "beg": ("/bɛɡ/", "BEG"),
    "peg": ("/pɛɡ/", "PEG"),
    "den": ("/dɛn/", "DEN"),
    "bit": ("/bɪt/", "BIT"),
    "hit": ("/hɪt/", "HIT"),
    "pit": ("/pɪt/", "PIT"),
    "fit": ("/fɪt/", "FIT"),
    "kit": ("/kɪt/", "KIT"),
    "dig": ("/dɪɡ/", "DIG"),
    "fin": ("/fɪn/", "FIN"),
    "pin": ("/pɪn/", "PIN"),
    "tin": ("/tɪn/", "TIN"),
    "bin": ("/bɪn/", "BIN"),
    "win": ("/wɪn/", "WIN"),
    "rip": ("/rɪp/", "RIP"),
    "lip": ("/lɪp/", "LIP"),
    "hip": ("/hɪp/", "HIP"),
    "dip": ("/dɪp/", "DIP"),
    "tip": ("/tɪp/", "TIP"),
    "fig": ("/fɪɡ/", "FIG"),
    "rig": ("/rɪɡ/", "RIG"),
    "sin": ("/sɪn/", "SIN"),
    "nib": ("/nɪb/", "NIB"),
    "pot": ("/pɑːt/", "PAHT"),
    "hop": ("/hɑːp/", "HAHP"),
    "pop": ("/pɑːp/", "PAHP"),
    "mop": ("/mɑːp/", "MAHP"),
    "dot": ("/dɑːt/", "DAHT"),
    "lot": ("/lɑːt/", "LAHT"),
    "jog": ("/dʒɑːɡ/", "JAWG"),
    "hog": ("/hɑːɡ/", "HAWG"),
    "fog": ("/fɑːɡ/", "FAWG"),
    "rod": ("/rɑːd/", "RAHD"),
    "nod": ("/nɑːd/", "NAHD"),
    "pod": ("/pɑːd/", "PAHD"),
    "cop": ("/kɑːp/", "KAHP"),
    "sob": ("/sɑːb/", "SAHB"),
    "rob": ("/rɑːb/", "RAHB"),
    "bug": ("/bʌɡ/", "BUG"),
    "nut": ("/nʌt/", "NUT"),
    "hut": ("/hʌt/", "HUT"),
    "cut": ("/kʌt/", "KUT"),
    "mud": ("/mʌd/", "MUD"),
    "cub": ("/kʌb/", "KUB"),
    "rub": ("/rʌb/", "RUB"),
    "hum": ("/hʌm/", "HUM"),
    "gum": ("/ɡʌm/", "GUM"),
    "pup": ("/pʌp/", "PUP"),
    "sub": ("/sʌb/", "SUB"),
    "bud": ("/bʌd/", "BUD"),
    "jug": ("/dʒʌɡ/", "JUG"),
    # Expanded blends
    "black": ("/blæk/", "BLAK"),
    "clap": ("/klæp/", "KLAP"),
    "grin": ("/ɡrɪn/", "GRIN"),
    "grip": ("/ɡrɪp/", "GRIP"),
    "plum": ("/plʌm/", "PLUM"),
    "snap": ("/snæp/", "SNAP"),
    "span": ("/spæn/", "SPAN"),
    "spin": ("/spɪn/", "SPIN"),
    "spot": ("/spɑːt/", "SPAHT"),
    "step": ("/stɛp/", "STEP"),
    "stem": ("/stɛm/", "STEM"),
    "twig": ("/twɪɡ/", "TWIG"),
    "twin": ("/twɪn/", "TWIN"),
    "brim": ("/brɪm/", "BRIM"),
    "skit": ("/skɪt/", "SKIT"),
    # Expanded digraphs
    "cheek": ("/tʃiːk/", "CHEEK"),
    "chess": ("/tʃɛs/", "CHES"),
    "sheep": ("/ʃiːp/", "SHEEP"),
    "thick": ("/θɪk/", "THIK"),
    "thank": ("/θæŋk/", "THANK"),
    "brush": ("/brʌʃ/", "BRUSH"),
    "lunch": ("/lʌntʃ/", "LUNCH"),
    "witch": ("/wɪtʃ/", "WITCH"),
    "peach": ("/piːtʃ/", "PEECH"),
    "bench": ("/bɛntʃ/", "BENCH"),
    # Grade 2 heart words
    "always": ("/ˈɔːlweɪz/", "AWL-wayz"),
    "before": ("/bɪˈfɔːr/", "bee-FOR"),
    "found": ("/faʊnd/", "FOWND"),
    "green": ("/ɡriːn/", "GREEN"),
    "know": ("/noʊ/", "NOH"),
    "laugh": ("/læf/", "LAF"),
    "read": ("/riːd/", "REED"),
    "right": ("/raɪt/", "RYTE"),
    "sleep": ("/sliːp/", "SLEEP"),
    "tell": ("/tɛl/", "TEL"),
    "their": ("/ðɛr/", "THAIR"),
    "very": ("/ˈvɛri/", "VER-ee"),
    "wash": ("/wɑːʃ/", "WAHSH"),
    "which": ("/wɪtʃ/", "WITCH"),
    "would": ("/wʊd/", "WOOD"),
    "around": ("/əˈraʊnd/", "uh-ROWND"),
    "because": ("/bɪˈkɔːz/", "bee-KAWZ"),
    "best": ("/bɛst/", "BEST"),
    "buy": ("/baɪ/", "BY"),
    "cold": ("/koʊld/", "KOHLD"),
    "does": ("/dʌz/", "DUZ"),
    "fast": ("/fæst/", "FAST"),
    "first": ("/fɜːrst/", "FURST"),
    "five": ("/faɪv/", "FYVE"),
    "give": ("/ɡɪv/", "GIV"),
    # Silent e
    "cake": ("/keɪk/", "KAYK"),
    "bike": ("/baɪk/", "BYKE"),
    "kite": ("/kaɪt/", "KYTE"),
    "home": ("/hoʊm/", "HOHM"),
    "note": ("/noʊt/", "NOHT"),
    "cute": ("/kjuːt/", "KYOOT"),
    "lake": ("/leɪk/", "LAYK"),
    "bake": ("/beɪk/", "BAYK"),
    "rope": ("/roʊp/", "ROHP"),
    "hope": ("/hoʊp/", "HOHP"),
    "tube": ("/tuːb/", "TOOB"),
    "cube": ("/kjuːb/", "KYOOB"),
    "bone": ("/boʊn/", "BOHN"),
    "cone": ("/koʊn/", "KOHN"),
    "dime": ("/daɪm/", "DYM"),
    "lime": ("/laɪm/", "LYM"),
    "ride": ("/raɪd/", "RYDE"),
    "slide": ("/slaɪd/", "SLYD"),
    "poke": ("/poʊk/", "POHK"),
    "grape": ("/ɡreɪp/", "GRAYP"),
    # Vowel teams
    "rain": ("/reɪn/", "RAYN"),
    "boat": ("/boʊt/", "BOHT"),
    "team": ("/tiːm/", "TEEM"),
    "feet": ("/fiːt/", "FEET"),
    "blue": ("/bluː/", "BLOO"),
    "mail": ("/meɪl/", "MAYL"),
    "tail": ("/teɪl/", "TAYL"),
    "coat": ("/koʊt/", "KOHT"),
    "goat": ("/ɡoʊt/", "GOHT"),
    "soap": ("/soʊp/", "SOHP"),
    "mean": ("/miːn/", "MEEN"),
    "bean": ("/biːn/", "BEEN"),
    "week": ("/wiːk/", "WEEK"),
    "peek": ("/piːk/", "PEEK"),
    "train": ("/treɪn/", "TRAYN"),
    "coin": ("/kɔɪn/", "KOIN"),
    "join": ("/dʒɔɪn/", "JOYN"),
    "cloud": ("/klaʊd/", "KLOWD"),
    # R-controlled
    "card": ("/kɑːrd/", "KARD"),
    "farm": ("/fɑːrm/", "FARM"),
    "horn": ("/hɔːrn/", "HORN"),
    "curl": ("/kɜːrl/", "KURL"),
    "corn": ("/kɔːrn/", "KORN"),
    "born": ("/bɔːrn/", "BORN"),
    "torn": ("/tɔːrn/", "TORN"),
    "hard": ("/hɑːrd/", "HARD"),
    "park": ("/pɑːrk/", "PARK"),
    "mark": ("/mɑːrk/", "MARK"),
    "dark": ("/dɑːrk/", "DARK"),
    "fork": ("/fɔːrk/", "FORK"),
    "turn": ("/tɜːrn/", "TERN"),
    "burn": ("/bɜːrn/", "BURN"),
    "surf": ("/sɜːrf/", "SURF"),
    # Expanded basic vocabulary
    "blue": ("/bluː/", "BLOO"),
    "pink": ("/pɪŋk/", "PINK"),
    "brown": ("/braʊn/", "BROWN"),
    "yellow": ("/ˈjɛloʊ/", "YEL-oh"),
    "four": ("/fɔːr/", "FOR"),
    "five": ("/faɪv/", "FYVE"),
    "seven": ("/ˈsɛvən/", "SEV-en"),
    "eight": ("/eɪt/", "AYT"),
    "nine": ("/naɪn/", "NYN"),
    "zero": ("/ˈzɪroʊ/", "ZEER-oh"),
    "bear": ("/ber/", "BAIR"),
    "duck": ("/dʌk/", "DUK"),
    "horse": ("/hɔːrs/", "HORSS"),
    "cow": ("/kaʊ/", "KOW"),
    "bee": ("/biː/", "BEE"),
    "bread": ("/brɛd/", "BRED"),
    "rice": ("/raɪs/", "RYSS"),
    "egg": ("/ɛɡ/", "EG"),
    "pizza": ("/ˈpiːtsə/", "PEET-suh"),
    "soup": ("/suːp/", "SOOP"),
    "head": ("/hɛd/", "HED"),
    "hand": ("/hænd/", "HAND"),
    "foot": ("/fʊt/", "FOOT"),
    "eye": ("/aɪ/", "EYE"),
    "spring": ("/sprɪŋ/", "SPRING"),
    "summer": ("/ˈsʌmər/", "SUM-er"),
    "winter": ("/ˈwɪntər/", "WIN-ter"),
    # Gr 3 heart words
    "about": ("/əˈbaʊt/", "uh-BOWT"),
    "better": ("/ˈbɛtər/", "BET-er"),
    "carry": ("/ˈkæri/", "KAR-ee"),
    "clean": ("/kliːn/", "KLEEN"),
    "earth": ("/ɜːrθ/", "URTH"),
    "fall": ("/fɔːl/", "FAWL"),
    "full": ("/fʊl/", "FUL"),
    "hold": ("/hoʊld/", "HOHLD"),
    "hurt": ("/hɜːrt/", "HURT"),
    "keep": ("/kiːp/", "KEEP"),
    "kind": ("/kaɪnd/", "KYND"),
    "long": ("/lɔːŋ/", "LAWNG"),
    "much": ("/mʌtʃ/", "MUCH"),
    "never": ("/ˈnɛvər/", "NEV-er"),
    "only": ("/ˈoʊnli/", "OHN-lee"),
    "own": ("/oʊn/", "OHN"),
    "pick": ("/pɪk/", "PIK"),
    "shall": ("/ʃæl/", "SHAL"),
    "show": ("/ʃoʊ/", "SHOH"),
    "start": ("/stɑːrt/", "START"),
    "today": ("/təˈdeɪ/", "tuh-DAY"),
    "together": ("/təˈɡɛðər/", "tuh-GETH-er"),
    "try": ("/traɪ/", "TRY"),
    "warm": ("/wɔːrm/", "WARM"),
    "also": ("/ˈɔːlsoʊ/", "AWL-soh"),
    "answer": ("/ˈænsər/", "AN-ser"),
    "city": ("/ˈsɪti/", "SIT-ee"),
    "famous": ("/ˈfeɪməs/", "FAY-mus"),
    "group": ("/ɡruːp/", "GROOP"),
    "listen": ("/ˈlɪsən/", "LIS-en"),
    "measure": ("/ˈmɛʒər/", "MEZH-er"),
    "question": ("/ˈkwɛstʃən/", "KWES-chun"),
    "special": ("/ˈspɛʃəl/", "SPESH-ul"),
    "surprise": ("/sərˈpraɪz/", "ser-PRYZ"),
    "though": ("/ðoʊ/", "THOH"),
    "young": ("/jʌŋ/", "YUNG"),
    # Gr 4 heart words
    "among": ("/əˈmʌŋ/", "uh-MUNG"),
    "caught": ("/kɔːt/", "KAWT"),
    "country": ("/ˈkʌntri/", "KUN-tree"),
    "early": ("/ˈɜːrli/", "UR-lee"),
    "example": ("/ɪɡˈzæmpəl/", "ig-ZAM-pul"),
    "field": ("/fiːld/", "FEELD"),
    "forest": ("/ˈfɔːrɪst/", "FOR-ist"),
    "history": ("/ˈhɪstəri/", "HIS-tuh-ree"),
    "island": ("/ˈaɪlənd/", "EYE-lund"),
    "language": ("/ˈlæŋɡwɪdʒ/", "LANG-gwij"),
    "notice": ("/ˈnoʊtɪs/", "NOH-tis"),
    "object": ("/ˈɑːbdʒɛkt/", "AHB-jekt"),
    "paragraph": ("/ˈpærəɡræf/", "PAR-uh-graf"),
    "passage": ("/ˈpæsɪdʒ/", "PAS-ij"),
    "planet": ("/ˈplænɪt/", "PLAN-it"),
    "problem": ("/ˈprɑːbləm/", "PRAH-blum"),
    "region": ("/ˈriːdʒən/", "REE-jun"),
    "remember": ("/rɪˈmɛmbər/", "ri-MEM-ber"),
    "science": ("/ˈsaɪəns/", "SY-ens"),
    "sentence": ("/ˈsɛntəns/", "SEN-tens"),
    "suppose": ("/səˈpoʊz/", "suh-POHZ"),
    "therefore": ("/ˈðɛrfɔːr/", "THAIR-for"),
    "vegetable": ("/ˈvɛdʒtəbəl/", "VEJ-tuh-bul"),
    "verb": ("/vɜːrb/", "VERB"),
    "whether": ("/ˈwɛðər/", "WETH-er"),
    "although": ("/ɔːlˈðoʊ/", "awl-THOH"),
    "amount": ("/əˈmaʊnt/", "uh-MOWNT"),
    "complete": ("/kəmˈpliːt/", "kum-PLEET"),
    "consider": ("/kənˈsɪdər/", "kun-SID-er"),
    "direction": ("/dɪˈrɛkʃən/", "di-REK-shun"),
    "discover": ("/dɪˈskʌvər/", "di-SKUV-er"),
    "important": ("/ɪmˈpɔːrtənt/", "im-POR-tunt"),
    "material": ("/məˈtɪriəl/", "muh-TIR-ee-ul"),
    "opposite": ("/ˈɑːpəzɪt/", "AH-puh-zit"),
    "possible": ("/ˈpɑːsəbəl/", "PAHS-uh-bul"),
    "probably": ("/ˈprɑːbəbli/", "PRAH-buh-lee"),
    "purpose": ("/ˈpɜːrpəs/", "PUR-pus"),
    # Multisyllable · Gr 3
    "animal": ("/ˈænɪməl/", "AN-uh-mul"),
    "basket": ("/ˈbæskɪt/", "BAS-kit"),
    "candle": ("/ˈkændəl/", "KAN-dul"),
    "carrot": ("/ˈkærət/", "KAR-ut"),
    "dinner": ("/ˈdɪnər/", "DIN-er"),
    "finger": ("/ˈfɪŋɡər/", "FING-er"),
    "happy": ("/ˈhæpi/", "HAP-ee"),
    "kitten": ("/ˈkɪtən/", "KIT-en"),
    "lemon": ("/ˈlɛmən/", "LEM-un"),
    "magic": ("/ˈmædʒɪk/", "MAJ-ik"),
    "monkey": ("/ˈmʌŋki/", "MUNG-kee"),
    "number": ("/ˈnʌmbər/", "NUM-ber"),
    "pencil": ("/ˈpɛnsəl/", "PEN-sul"),
    "pocket": ("/ˈpɑːkɪt/", "PAH-kit"),
    "pumpkin": ("/ˈpʌmpkɪn/", "PUMP-kin"),
    "rabbit": ("/ˈræbɪt/", "RAB-it"),
    "rocket": ("/ˈrɑːkɪt/", "RAH-kit"),
    "silver": ("/ˈsɪlvər/", "SIL-ver"),
    "trumpet": ("/ˈtrʌmpɪt/", "TRUMP-it"),
    "window": ("/ˈwɪndoʊ/", "WIN-doh"),
    "blanket": ("/ˈblæŋkɪt/", "BLANG-kit"),
    "golden": ("/ˈɡoʊldən/", "GOHL-den"),
    "happen": ("/ˈhæpən/", "HAP-un"),
    "jacket": ("/ˈdʒækɪt/", "JAK-it"),
    "lesson": ("/ˈlɛsən/", "LES-un"),
    "market": ("/ˈmɑːrkɪt/", "MAR-kit"),
    "napkin": ("/ˈnæpkɪn/", "NAP-kin"),
    "picnic": ("/ˈpɪknɪk/", "PIK-nik"),
    "ticket": ("/ˈtɪkɪt/", "TIK-it"),
    "travel": ("/ˈtrævəl/", "TRAV-ul"),
    # Prefix & suffix · Gr 4
    "preview": ("/ˈpriːvjuː/", "PREE-vyoo"),
    "reread": ("/riːˈriːd/", "ree-REED"),
    "subway": ("/ˈsʌbweɪ/", "SUB-way"),
    "unhappy": ("/ʌnˈhæpi/", "un-HAP-ee"),
    "refill": ("/riːˈfɪl/", "ree-FIL"),
    "rewrite": ("/riːˈraɪt/", "ree-RYTE"),
    "hopeful": ("/ˈhoʊpfəl/", "HOHP-ful"),
    "joyful": ("/ˈdʒɔɪfəl/", "JOY-ful"),
    "quickly": ("/ˈkwɪkli/", "KWIK-lee"),
    "slowly": ("/ˈsloʊli/", "SLOH-lee"),
    "baking": ("/ˈbeɪkɪŋ/", "BAY-king"),
    "running": ("/ˈrʌnɪŋ/", "RUN-ing"),
    "jumped": ("/dʒʌmpt/", "JUMPT"),
    "playing": ("/ˈpleɪɪŋ/", "PLAY-ing"),
    "kindness": ("/ˈkaɪndnəs/", "KYND-nis"),
    "darkness": ("/ˈdɑːrknəs/", "DARK-nis"),
    "helpful": ("/ˈhɛlpfəl/", "HELP-ful"),
    "careful": ("/ˈkerfəl/", "KAIR-ful"),
    "fearless": ("/ˈfɪrləs/", "FEER-lis"),
    "powerful": ("/ˈpaʊərfəl/", "POW-er-ful"),
    "weakness": ("/ˈwiːknəs/", "WEEK-nis"),
    "movement": ("/ˈmuːvmənt/", "MOOV-munt"),
    "payment": ("/ˈpeɪmənt/", "PAY-munt"),
    "teacher": ("/ˈtiːtʃər/", "TEE-chur"),
    # Basic · Gr 3–4
    "ocean": ("/ˈoʊʃən/", "OH-shun"),
    "mountain": ("/ˈmaʊntən/", "MOWN-tin"),
    "desert": ("/ˈdɛzərt/", "DEZ-ert"),
    "hurricane": ("/ˈhɜːrəkeɪn/", "HUR-uh-kayn"),
    "dinosaur": ("/ˈdaɪnəsɔːr/", "DY-nuh-sor"),
    "cafeteria": ("/ˌkæfəˈtɪriə/", "kaf-uh-TIR-ee-uh"),
    "museum": ("/mjuˈziːəm/", "myoo-ZEE-um"),
    "hospital": ("/ˈhɑːspɪtl/", "HAHS-pih-tul"),
    "rectangle": ("/ˈrɛktæŋɡəl/", "REK-tang-gul"),
    "triangle": ("/ˈtraɪæŋɡəl/", "TRY-ang-gul"),
    "alphabet": ("/ˈælfəbɛt/", "AL-fuh-bet"),
    "dictionary": ("/ˈdɪkʃəneri/", "DIK-shuh-ner-ee"),
    "autumn": ("/ˈɔːtəm/", "AW-tum"),
    "calendar": ("/ˈkæləndər/", "KAL-un-der"),
    "compass": ("/ˈkʌmpəs/", "KUM-pus"),
    "volcano": ("/vɑːlˈkeɪnoʊ/", "vahl-KAY-noh"),
    "tornado": ("/tɔːrˈneɪdoʊ/", "tor-NAY-doh"),
    "galaxy": ("/ˈɡæləksi/", "GAL-uk-see"),
    "microscope": ("/ˈmaɪkrəskoʊp/", "MY-kruh-skohp"),
    "telescope": ("/ˈtɛləskoʊp/", "TEL-uh-skohp"),
    "encyclopedia": ("/ɪnˌsaɪkləˈpiːdiə/", "in-SY-kluh-PEE-dee-uh"),
    "peninsula": ("/pəˈnɪnsələ/", "puh-NIN-suh-luh"),
    "equator": ("/ɪˈkweɪtər/", "ih-KWAY-ter"),
    "geography": ("/dʒiˈɑːɡrəfi/", "jee-AH-gruh-fee"),
    "civilization": ("/ˌsɪvələˈzeɪʃən/", "siv-uh-luh-ZAY-shun"),
    "electricity": ("/ɪˌlɛkˈtrɪsɪti/", "ih-lek-TRIS-ih-tee"),
    "temperature": ("/ˈtɛmpərətʃər/", "TEMP-er-uh-chur"),
    "experiment": ("/ɪkˈspɛrəmənt/", "ik-SPER-uh-munt"),
    "multiplication": ("/ˌmʌltəplɪˈkeɪʃən/", "mul-tuh-pli-KAY-shun"),
    "division": ("/dɪˈvɪʒən/", "di-VIJ-un"),
    # Minecraft
    "grass": ("/ɡræs/", "GRASS"),
    "dirt": ("/dɜːrt/", "DURT"),
    "stone": ("/stoʊn/", "STOHN"),
    "sand": ("/sænd/", "SAND"),
    "gravel": ("/ˈɡrævəl/", "GRAV-ul"),
    "clay": ("/kleɪ/", "KLAY"),
    "brick": ("/brɪk/", "BRIK"),
    "obsidian": ("/əbˈsɪdiən/", "ub-SID-ee-un"),
    "bedrock": ("/ˈbɛdrɑːk/", "BED-rahk"),
    "cobblestone": ("/ˈkɑːbəlstoʊn/", "KAH-bul-stohn"),
    "plank": ("/plæŋk/", "PLANK"),
    "ore": ("/ɔːr/", "OR"),
    "emerald": ("/ˈɛmərəld/", "EM-er-uld"),
    "redstone": ("/ˈrɛdtoʊn/", "RED-stohn"),
    "copper": ("/ˈkɑːpər/", "KAH-per"),
    "coal": ("/koʊl/", "KOHL"),
    "iron": ("/ˈaɪərn/", "EYE-urn"),
    "gold": ("/ɡoʊld/", "GOHLD"),
    "diamond": ("/ˈdaɪmənd/", "DY-mund"),
    "netherite": ("/ˈnɛðəraɪt/", "NETH-er-yte"),
    "lava": ("/ˈlɑːvə/", "LAH-vuh"),
    "netherrack": ("/ˈnɛðəræk/", "NETH-er-rak"),
    "glowstone": ("/ˈɡloʊstoʊn/", "GLOH-stohn"),
    "wool": ("/wʊl/", "WUL"),
    "glass": ("/ɡlæs/", "GLASS"),
    "ice": ("/aɪs/", "EYESS"),
    "snow": ("/snoʊ/", "SNOH"),
    "wood": ("/wʊd/", "WUD"),
    "tnt": ("/tiːɛnˈtiː/", "T-N-T"),
    "sponge": ("/spʌndʒ/", "SPUNJ"),
    "zombie": ("/ˈzɑːmbi/", "ZOM-bee"),
    "skeleton": ("/ˈskɛlətən/", "SKEL-uh-tun"),
    "spider": ("/ˈspaɪdər/", "SPY-der"),
    "creeper": ("/ˈkriːpər/", "KREE-per"),
    "enderman": ("/ˈɛndərmæn/", "EN-der-man"),
    "villager": ("/ˈvɪlɪdʒər/", "VIL-ij-er"),
    "piglin": ("/ˈpɪɡlɪn/", "PIG-lin"),
    "ghast": ("/ɡæst/", "GAST"),
    "blaze": ("/bleɪz/", "BLAYZ"),
    "slime": ("/slaɪm/", "SLYM"),
    "wolf": ("/wʊlf/", "WULF"),
    "chicken": ("/ˈtʃɪkən/", "CHIK-en"),
    "dragon": ("/ˈdræɡən/", "DRAG-un"),
    "wither": ("/ˈwɪðər/", "WITH-er"),
    "guardian": ("/ˈɡɑːrdiən/", "GAR-dee-un"),
    "phantom": ("/ˈfæntəm/", "FAN-tum"),
    "drowned": ("/draʊnd/", "DROWND"),
    "husk": ("/hʌsk/", "HUSK"),
    "stray": ("/streɪ/", "STRAY"),
    "ocelot": ("/ˈoʊsəˌlɑːt/", "OH-suh-laht"),
    "panda": ("/ˈpændə/", "PAN-duh"),
    "axolotl": ("/ˈæksəlɑːtəl/", "AK-suh-lah-tul"),
    "warden": ("/ˈwɔːrdən/", "WOR-den"),
    "allay": ("/əˈleɪ/", "uh-LAY"),
    "dolphin": ("/ˈdɑːlfɪn/", "DAHL-fin"),
    "squid": ("/skwɪd/", "SKWID"),
    "turtle": ("/ˈtɜːrtəl/", "TUR-tul"),
    "llama": ("/ˈlɑːmə/", "LAH-muh"),
    "camel": ("/ˈkæməl/", "KAM-ul"),
    "sniffer": ("/ˈsnɪfər/", "SNIF-er"),
    "sword": ("/sɔːrd/", "SORD"),
    "pickaxe": ("/ˈpɪkæks/", "PIK-aks"),
    "axe": ("/æks/", "AKS"),
    "shovel": ("/ˈʃʌvəl/", "SHUV-ul"),
    "hoe": ("/hoʊ/", "HOH"),
    "bow": ("/boʊ/", "BOH"),
    "arrow": ("/ˈɛroʊ/", "AIR-oh"),
    "shield": ("/ʃiːld/", "SHEELD"),
    "armor": ("/ˈɑːrmər/", "AR-mur"),
    "helmet": ("/ˈhɛlmɪt/", "HEL-mit"),
    "chestplate": ("/ˈtʃɛstpleɪt/", "CHEST-playt"),
    "leggings": ("/ˈlɛɡɪŋz/", "LEG-ingz"),
    "boots": ("/buːts/", "BOOTS"),
    "torch": ("/tɔːrtʃ/", "TORCH"),
    "lantern": ("/ˈlæntərn/", "LAN-tern"),
    "bucket": ("/ˈbʌkɪt/", "BUK-it"),
    "flint": ("/flɪnt/", "FLINT"),
    "shears": ("/ʃɪrz/", "SHEERZ"),
    "saddle": ("/ˈsædəl/", "SAD-ul"),
    "lead": ("/lɛd/", "LED"),
    "minecart": ("/ˈmaɪnkɑːrt/", "MYN-kart"),
    "chest": ("/tʃɛst/", "CHEST"),
    "furnace": ("/ˈfɜːrnɪs/", "FUR-nis"),
    "anvil": ("/ˈænvɪl/", "AN-vil"),
    "piston": ("/ˈpɪstən/", "PIS-tun"),
    "dispenser": ("/dɪˈspɛnsər/", "di-SPEN-ser"),
    "hopper": ("/ˈhɑːpər/", "HAH-per"),
    "lever": ("/ˈlɛvər/", "LEV-er"),
    "button": ("/ˈbʌtən/", "BUT-un"),
    "rail": ("/reɪl/", "RAYL"),
    "ladder": ("/ˈlædər/", "LAD-er"),
    "fence": ("/fɛns/", "FENS"),
    "gate": ("/ɡeɪt/", "GAYT"),
    "trapdoor": ("/ˈtræpdɔːr/", "TRAP-dor"),
    "beacon": ("/ˈbiːkən/", "BEE-kun"),
    "bookshelf": ("/ˈbʊkʃɛlf/", "BOOK-shelf"),
    "portal": ("/ˈpɔːrtəl/", "POR-tul"),
    "village": ("/ˈvɪlɪdʒ/", "VIL-ij"),
    "temple": ("/ˈtɛmpəl/", "TEM-pul"),
    "fortress": ("/ˈfɔːrtrəs/", "FOR-tress"),
    "dungeon": ("/ˈdʌndʒən/", "DUN-jun"),
    "mineshaft": ("/ˈmaɪnʃæft/", "MYN-shaft"),
    "nether": ("/ˈnɛðər/", "NETH-er"),
    "overworld": ("/ˈoʊvərwɜːrld/", "OH-ver-wurld"),
    "biome": ("/ˈbaɪoʊm/", "BY-ohm"),
    "cave": ("/keɪv/", "KAYV"),
    "jungle": ("/ˈdʒʌŋɡəl/", "JUNG-gul"),
    "swamp": ("/swɑːmp/", "SWAHMP"),
    "ravine": ("/rəˈviːn/", "ruh-VEEN"),
    "stronghold": ("/ˈstrɔːnhoʊld/", "STRAWN-hohld"),
    "craft": ("/kræft/", "KRAFT"),
    "mine": ("/maɪn/", "MYN"),
    "build": ("/bɪld/", "BILD"),
    "spawn": ("/spɔːn/", "SPAWN"),
    "world": ("/wɜːrld/", "WURLD"),
    "seed": ("/siːd/", "SEED"),
    "player": ("/ˈpleɪər/", "PLAY-er"),
    "mob": ("/mɑːb/", "MAHB"),
    "item": ("/ˈaɪtəm/", "EYE-tum"),
    "inventory": ("/ˈɪnvənˌtɔːri/", "IN-ven-tor-ee"),
    "hotbar": ("/ˈhɑːtbɑːr/", "HAHT-bar"),
    "enchant": ("/ɪnˈtʃænt/", "in-CHANT"),
    "survival": ("/sərˈvaɪvəl/", "ser-VY-vul"),
    "creative": ("/kriˈeɪtɪv/", "kree-AY-tiv"),
    "farming": ("/ˈfɑːrmɪŋ/", "FAR-ming"),
    "mining": ("/ˈmaɪnɪŋ/", "MYN-ing"),
    "trading": ("/ˈtreɪdɪŋ/", "TRAY-ding"),
    "brewing": ("/ˈbruːɪŋ/", "BROO-ing"),
    "smelting": ("/ˈsmɛltɪŋ/", "SMELT-ing"),
    "respawn": ("/riːˈspɔːn/", "ree-SPAWN"),
    "harvest": ("/ˈhɑːrvɪst/", "HAR-vist"),
    "explore": ("/ɪkˈsplɔːr/", "ik-SPLOR"),
    "tame": ("/teɪm/", "TAYM"),
    "breed": ("/briːd/", "BREED"),
    "smelt": ("/smɛlt/", "SMELT"),
    "loot": ("/luːt/", "LOOT"),
    "stack": ("/stæk/", "STAK"),
    "health": ("/hɛlθ/", "HELTH"),
    "hunger": ("/ˈhʌŋɡər/", "HUNG-er"),
    "experience": ("/ɪkˈspɪriəns/", "ik-SPEER-ee-ens"),
    "adventure": ("/ədˈvɛntʃər/", "ad-VEN-chur"),
    "crafting": ("/ˈkræftɪŋ/", "KRAFT-ing"),
    "stew": ("/stuː/", "STOO"),
    "honey": ("/ˈhʌni/", "HUN-ee"),
    "steak": ("/steɪk/", "STAYK"),
    "melon": ("/ˈmɛlən/", "MEL-un"),
    "berry": ("/ˈbɛri/", "BER-ee"),
    "mushroom": ("/ˈmʌʃruːm/", "MUSH-room"),
    "sapling": ("/ˈsæplɪŋ/", "SAP-ling"),
    "kelp": ("/kɛlp/", "KELP"),
    "coral": ("/ˈkɔːrəl/", "KOR-ul"),
    "repeater": ("/rɪˈpiːtər/", "ri-PEE-ter"),
    "comparator": ("/kəmˈpærətər/", "kum-PAR-uh-ter"),
    "observer": ("/əbˈzɜːrvər/", "ub-ZUR-ver"),
    "pearl": ("/pɜːrl/", "PURL"),
    "crystal": ("/ˈkrɪstəl/", "KRIS-tul"),
    "shulker": ("/ˈʃʊlkər/", "SHUL-ker"),
    "chorus": ("/ˈkɔːrəs/", "KOR-us"),
    "quartz": ("/kwɔːrts/", "KWARTS"),
    "lapis": ("/ˈleɪpɪs/", "LAY-pis"),
    "prismarine": ("/ˈprɪzməriːn/", "PRIZ-muh-reen"),
    "sculk": ("/skʌlk/", "SKULK"),
    "enchanting": ("/ɪnˈtʃæntɪŋ/", "in-CHANT-ing"),
    "potion": ("/ˈpoʊʃən/", "POH-shun"),
    "enchantment": ("/ɪnˈtʃæntmənt/", "in-CHANT-munt"),
}


def _r(
    word: str,
    emoji: str,
    chinese: str,
    type_: str,
    difficulty: int,
    word_type: str,
    grade: str,
) -> dict:
    return {
        "word": word,
        "emoji": emoji,
        "chinese": chinese,
        "type": type_,
        "difficulty": difficulty,
        "wordType": word_type,
        "gradeLevel": grade,
    }


# 127 CVC · K (short a/e/i/o/u; no sight-word overlap)
_CVC = [
    # — existing —
    ("cat", "🐱", "猫"),
    ("dog", "🐶", "狗"),
    ("sun", "☀️", "太阳"),
    ("bed", "🛏️", "床"),
    ("pen", "✏️", "笔"),
    ("cup", "🥤", "杯子"),
    ("map", "🗺️", "地图"),
    ("hat", "🎩", "帽子"),
    ("pig", "🐷", "猪"),
    ("bat", "🏏", "球棒"),
    ("bus", "🚌", "巴士"),
    ("red", "🔴", "红色"),
    ("run", "🏃", "跑"),
    ("sit", "🧘", "坐"),
    ("top", "🔝", "顶"),
    ("hot", "🌶️", "热"),
    ("big", "⬆️", "大"),
    ("bag", "👜", "包"),
    ("leg", "🦵", "腿"),
    ("man", "👨", "男人"),
    ("fan", "🪭", "扇子"),
    ("pan", "🍳", "平底锅"),
    ("cap", "🧢", "鸭舌帽"),
    ("net", "🥅", "网"),
    ("jet", "✈️", "喷气机"),
    ("log", "🪵", "原木"),
    ("van", "🚐", "货车"),
    ("web", "🕸️", "网"),
    ("wig", "💇", "假发"),
    ("zip", "🤐", "拉链"),
    ("box", "📦", "盒子"),
    ("fox", "🦊", "狐狸"),
    ("six", "6️⃣", "六"),
    ("rug", "🟫", "地毯"),
    ("tug", "🪢", "拽"),
    ("mug", "☕", "马克杯"),
    ("bun", "🥯", "小面包"),
    ("fun", "🎉", "好玩"),
    ("hen", "🐔", "母鸡"),
    ("cob", "🌽", "玉米棒"),
    ("dad", "👨", "爸爸"),
    ("mom", "👩", "妈妈"),
    ("car", "🚗", "汽车"),
    ("ant", "🐜", "蚂蚁"),
    ("tub", "🛁", "浴缸"),
    ("hug", "🤗", "抱"),
    ("pet", "🐾", "宠物"),
    ("jam", "🍓", "果酱"),
    # — short a —
    ("mat", "🧶", "垫子"),
    ("sat", "🪑", "坐"),
    ("rat", "🐀", "老鼠"),
    ("fat", "🍔", "胖"),
    ("pat", "👋", "拍"),
    ("wag", "🐕", "摇尾"),
    ("tag", "🏷️", "标签"),
    ("ham", "🍖", "火腿"),
    ("ram", "🐏", "公羊"),
    ("tab", "📑", "标签页"),
    ("sad", "😢", "难过"),
    ("mad", "😠", "生气"),
    ("pad", "📝", "便签本"),
    ("lap", "🦵", "大腿"),
    ("tap", "🚰", "轻敲"),
    ("nap", "😴", "小睡"),
    ("gap", "↔️", "缝隙"),
    ("sap", "🌲", "树液"),
    ("yak", "🐂", "牦牛"),
    ("vat", "🛢️", "大桶"),
    # — short e —
    ("bet", "🎲", "打赌"),
    ("let", "✋", "让"),
    ("ten", "🔟", "十"),
    ("men", "👨", "男人们"),
    ("wet", "💧", "湿"),
    ("set", "📦", "一套"),
    ("met", "🤝", "遇见"),
    ("vet", "👨‍⚕️", "兽医"),
    ("beg", "🙏", "乞求"),
    ("peg", "📌", "木钉"),
    ("den", "🦁", "兽穴"),
    # — short i —
    ("bit", "🔩", "一点"),
    ("hit", "👊", "打"),
    ("pit", "🕳️", "坑"),
    ("fit", "✅", "合适"),
    ("kit", "🧰", "工具包"),
    ("dig", "⛏️", "挖"),
    ("fin", "🦈", "鱼鳍"),
    ("pin", "📍", "别针"),
    ("tin", "🥫", "锡"),
    ("bin", "🗑️", "箱子"),
    ("win", "🏆", "赢"),
    ("rip", "📄", "撕"),
    ("lip", "👄", "嘴唇"),
    ("hip", "🦴", "髋"),
    ("dip", "🫕", "蘸"),
    ("tip", "💡", "小费；尖端"),
    ("fig", "🍇", "无花果"),
    ("rig", "🛢️", "钻机"),
    ("sin", "😈", "罪"),
    ("nib", "✒️", "笔尖"),
    # — short o —
    ("pot", "🍲", "锅"),
    ("hop", "🐇", "单脚跳"),
    ("pop", "🎈", "砰"),
    ("mop", "🧹", "拖把"),
    ("dot", "⚫", "点"),
    ("lot", "🅿️", "一块地"),
    ("jog", "🏃", "慢跑"),
    ("hog", "🐷", "猪"),
    ("fog", "🌫️", "雾"),
    ("rod", "🎣", "杆"),
    ("nod", "👍", "点头"),
    ("pod", "🫛", "豆荚"),
    ("cop", "👮", "警察"),
    ("sob", "😭", "抽泣"),
    ("rob", "🦹", "抢"),
    # — short u —
    ("bug", "🐛", "虫子"),
    ("nut", "🥜", "坚果"),
    ("hut", "🏕️", "小屋"),
    ("cut", "✂️", "剪"),
    ("mud", "🟤", "泥"),
    ("cub", "🐻", "幼崽"),
    ("rub", "🤲", "揉"),
    ("hum", "🎵", "哼唱"),
    ("gum", "🫧", "口香糖"),
    ("pup", "🐶", "小狗"),
    ("sub", "🥪", "潜艇；三明治"),
    ("bud", "🌱", "芽"),
    ("jug", "🫙", "壶"),
]

# 35 blends · Gr 1
_BLEND = [
    ("flag", "🚩", "旗"),
    ("plug", "🔌", "塞子"),
    ("drum", "🥁", "鼓"),
    ("frog", "🐸", "青蛙"),
    ("plan", "📋", "计划"),
    ("block", "🧱", "积木"),
    ("club", "♣️", "俱乐部"),
    ("crop", "🌾", "庄稼"),
    ("star", "⭐", "星星"),
    ("stop", "🛑", "停"),
    ("swim", "🏊", "游泳"),
    ("sled", "🛷", "雪橇"),
    ("trim", "✂️", "修剪"),
    ("trap", "🪤", "陷阱"),
    ("crib", "🛏️", "婴儿床"),
    ("grab", "✊", "抓"),
    ("glad", "😊", "高兴"),
    ("flip", "🤸", "翻"),
    ("clip", "📎", "夹子"),
    ("drop", "💧", "滴"),
    ("black", "⬛", "黑色"),
    ("clap", "👏", "拍手"),
    ("grin", "😁", "咧嘴笑"),
    ("grip", "✊", "紧握"),
    ("plum", "🍑", "李子"),
    ("snap", "📸", "啪"),
    ("span", "↔️", "跨度"),
    ("spin", "🌀", "旋转"),
    ("spot", "🔴", "斑点"),
    ("step", "👣", "脚步"),
    ("stem", "🌿", "茎"),
    ("twig", "🌿", "细枝"),
    ("twin", "👯", "双胞胎"),
    ("brim", "🎩", "帽檐"),
    ("skit", "🎭", "短剧"),
]

# 30 digraphs · Gr 1
_DIGRAPH = [
    ("ship", "🚢", "船"),
    ("chip", "🥔", "薯片"),
    ("fish", "🐟", "鱼"),
    ("shoe", "👟", "鞋"),
    ("chat", "💬", "聊天"),
    ("shop", "🛒", "商店"),
    ("shell", "🐚", "贝壳"),
    ("dish", "🍽️", "盘子"),
    ("wish", "🌠", "愿望"),
    ("chop", "🔪", "砍"),
    ("chin", "🙂", "下巴"),
    ("math", "➕", "数学"),
    ("path", "🛤️", "小路"),
    ("bath", "🛁", "洗澡"),
    ("moth", "🦋", "蛾"),
    ("thin", "📏", "薄"),
    ("that", "👉", "那"),
    ("then", "⏭️", "然后"),
    ("white", "⚪", "白色"),
    ("whale", "🐋", "鲸"),
    ("cheek", "😊", "脸颊"),
    ("chess", "♟️", "国际象棋"),
    ("sheep", "🐑", "绵羊"),
    ("thick", "📚", "厚的"),
    ("thank", "🙏", "感谢"),
    ("brush", "🖌️", "刷子"),
    ("lunch", "🍱", "午餐"),
    ("witch", "🧙", "女巫"),
    ("peach", "🍑", "桃子"),
    ("bench", "🪑", "长凳"),
]

# 20 silent e · Gr 1
_SILENT_E = [
    ("cake", "🎂", "蛋糕"),
    ("bike", "🚲", "自行车"),
    ("kite", "🪁", "风筝"),
    ("home", "🏠", "家"),
    ("note", "🎵", "音符；便条"),
    ("cute", "🥰", "可爱"),
    ("lake", "🏞️", "湖"),
    ("bake", "🥖", "烘烤"),
    ("rope", "🪢", "绳子"),
    ("hope", "🤞", "希望"),
    ("tube", "🧪", "管子"),
    ("cube", "🧊", "立方体"),
    ("bone", "🦴", "骨头"),
    ("cone", "🍦", "甜筒"),
    ("dime", "🪙", "一角硬币"),
    ("lime", "🍋", "青柠"),
    ("ride", "🎢", "乘坐"),
    ("slide", "🛝", "滑梯"),
    ("poke", "👉", "戳"),
    ("grape", "🍇", "葡萄"),
]

# 18 vowel teams · Gr 1
_VOWEL_TEAM = [
    ("rain", "🌧️", "雨"),
    ("boat", "⛵", "船"),
    ("team", "👥", "队伍"),
    ("feet", "🦶", "脚（复数）"),
    ("blue", "🔵", "蓝色"),
    ("mail", "✉️", "邮件"),
    ("tail", "🐕", "尾巴"),
    ("coat", "🧥", "外套"),
    ("goat", "🐐", "山羊"),
    ("soap", "🧼", "肥皂"),
    ("mean", "😠", "刻薄；意思是"),
    ("bean", "🫘", "豆子"),
    ("week", "📅", "星期"),
    ("peek", "👀", "偷看"),
    ("train", "🚂", "火车"),
    ("coin", "🪙", "硬币"),
    ("join", "🤝", "加入"),
    ("cloud", "☁️", "云"),
]

# 15 r-controlled · Gr 2
_R_CONTROLLED = [
    ("card", "🃏", "卡片"),
    ("farm", "🚜", "农场"),
    ("horn", "📯", "号角"),
    ("curl", "🌀", "卷曲"),
    ("corn", "🌽", "玉米"),
    ("born", "👶", "出生"),
    ("torn", "📄", "撕破"),
    ("hard", "💪", "难；硬"),
    ("park", "🏞️", "公园"),
    ("mark", "✏️", "标记"),
    ("dark", "🌙", "黑暗"),
    ("fork", "🍴", "叉子"),
    ("turn", "↩️", "转弯"),
    ("burn", "🔥", "燃烧"),
    ("surf", "🏄", "冲浪"),
]

# Heart words · K
_SIGHT_K = [
    ("the", "✨", "这；那个"),
    ("and", "➕", "和"),
    ("you", "🫵", "你"),
    ("is", "ℹ️", "是"),
    ("it", "📌", "它"),
    ("in", "📥", "在…里"),
    ("on", "📍", "在…上"),
    ("to", "➡️", "向；到"),
    ("we", "🧑‍🤝‍🧑", "我们"),
    ("go", "🚶", "去"),
    ("me", "🙋", "我"),
    ("a", "🔤", "一个（冠词）"),
    ("see", "👀", "看见"),
    ("my", "🧒", "我的"),
    ("can", "💪", "能"),
    ("look", "👀", "看"),
    ("like", "👍", "喜欢"),
    ("here", "📍", "这里"),
    ("come", "🚶‍➡️", "来"),
    ("one", "1️⃣", "一"),
    ("two", "2️⃣", "二"),
    ("three", "3️⃣", "三"),
    ("up", "⬆️", "上"),
    ("down", "⬇️", "下"),
    ("yes", "✅", "是"),
    ("no", "❎", "不"),
    ("help", "🆘", "帮助"),
    ("jump", "🦘", "跳"),
    ("he", "👦", "他"),
    ("his", "🏷️", "他的"),
    ("her", "👧", "她；她的"),
    ("at", "🎯", "在"),
    ("for", "🎁", "为了"),
    ("get", "🤲", "得到"),
    ("not", "🚫", "不"),
    ("so", "✨", "所以；很"),
    ("day", "🌤️", "天；日子"),
    ("want", "🙏", "想要"),
    ("this", "👆", "这个"),
    ("good", "👍", "好"),
    ("all", "🔁", "全部"),
    ("out", "🚪", "外；出"),
    ("make", "🛠️", "做"),
    ("say", "💬", "说"),
    ("your", "👉", "你的"),
    ("funny", "😂", "好笑"),
    ("little", "🤏", "小"),
]
_SIGHT_1 = [
    ("they", "👥", "他们"),
    ("have", "📦", "有"),
    ("said", "💬", "说"),
    ("from", "📤", "从"),
    ("what", "❓", "什么"),
    ("when", "🕐", "何时"),
    ("where", "🧭", "哪里"),
    ("why", "🤔", "为什么"),
    ("how", "❔", "怎样"),
    ("could", "🔮", "能"),
    ("was", "⏪", "是"),
    ("are", "↔️", "是"),
    ("now", "📍", "现在"),
    ("she", "👩", "她"),
    ("some", "🤲", "一些"),
    ("there", "👉", "那里"),
    ("an", "📝", "一个"),
    ("him", "👦", "他（宾格）"),
    ("has", "📦", "有（三单）"),
    ("had", "📜", "有过"),
    ("were", "👥", "是（are 的过去）"),
    ("into", "📥", "进入"),
    ("off", "⏹️", "离开；关掉"),
    ("our", "🧑‍🤝‍🧑", "我们的"),
    ("ask", "🙋", "问"),
]

# 25 heart words · Gr 2
_SIGHT_2 = [
    ("always", "♾️", "总是"),
    ("before", "⏮️", "在…之前"),
    ("found", "🔍", "找到"),
    ("green", "🟢", "绿色"),
    ("know", "🧠", "知道"),
    ("laugh", "😂", "笑"),
    ("read", "📖", "读"),
    ("right", "✅", "对；右边"),
    ("sleep", "😴", "睡觉"),
    ("tell", "🗣️", "告诉"),
    ("their", "👥", "他们的"),
    ("very", "⭐", "非常"),
    ("wash", "🧼", "洗"),
    ("which", "❓", "哪一个"),
    ("would", "💭", "会；愿意"),
    ("around", "🔄", "周围"),
    ("because", "💡", "因为"),
    ("best", "🏆", "最好"),
    ("buy", "🛒", "买"),
    ("cold", "🥶", "冷"),
    ("does", "❓", "做（三单）"),
    ("fast", "⚡", "快"),
    ("first", "1️⃣", "第一"),
    ("five", "5️⃣", "五"),
    ("give", "🎁", "给"),
]

# 40 basic vocabulary · K–2
_BASIC = [
    ("apple", "🍎", "苹果", 2, "K"),
    ("banana", "🍌", "香蕉", 3, "1"),
    ("ball", "⚽", "球", 2, "K"),
    ("tree", "🌳", "树", 2, "K"),
    ("bird", "🐦", "鸟", 2, "K"),
    ("water", "💧", "水", 2, "K"),
    ("milk", "🥛", "牛奶", 2, "K"),
    ("book", "📚", "书", 2, "K"),
    ("door", "🚪", "门", 2, "K"),
    ("house", "🏠", "房子", 3, "1"),
    ("school", "🏫", "学校", 3, "1"),
    ("teacher", "👩‍🏫", "老师", 3, "1"),
    ("friend", "🤝", "朋友", 3, "1"),
    ("family", "👪", "家庭", 3, "1"),
    ("play", "🎮", "玩", 2, "K"),
    ("pink", "🩷", "粉色", 2, "K"),
    ("brown", "🟤", "棕色", 2, "K"),
    ("yellow", "🟡", "黄色", 2, "K"),
    ("four", "4️⃣", "四", 2, "K"),
    ("seven", "7️⃣", "七", 2, "K"),
    ("eight", "8️⃣", "八", 2, "K"),
    ("nine", "9️⃣", "九", 2, "K"),
    ("zero", "0️⃣", "零", 2, "K"),
    ("bear", "🐻", "熊", 2, "K"),
    ("duck", "🦆", "鸭子", 2, "K"),
    ("horse", "🐴", "马", 2, "K"),
    ("cow", "🐄", "牛", 2, "K"),
    ("bee", "🐝", "蜜蜂", 2, "K"),
    ("bread", "🍞", "面包", 2, "K"),
    ("rice", "🍚", "米饭", 2, "K"),
    ("egg", "🥚", "鸡蛋", 2, "K"),
    ("pizza", "🍕", "披萨", 3, "1"),
    ("soup", "🍲", "汤", 2, "K"),
    ("head", "🗣️", "头", 2, "K"),
    ("hand", "✋", "手", 2, "K"),
    ("foot", "🦶", "脚", 2, "K"),
    ("eye", "👁️", "眼睛", 2, "K"),
    ("spring", "🌸", "春天", 3, "1"),
    ("summer", "☀️", "夏天", 3, "1"),
    ("winter", "❄️", "冬天", 3, "1"),
]

# 30 heart words · Gr 3
_SIGHT_3 = [
    ("about", "💬", "关于"),
    ("better", "⬆️", "更好"),
    ("carry", "🎒", "携带"),
    ("clean", "🧹", "干净"),
    ("earth", "🌍", "地球"),
    ("fall", "🍂", "落下；秋天"),
    ("full", "🫙", "满的"),
    ("hold", "🤲", "握住"),
    ("hurt", "🤕", "受伤"),
    ("keep", "🔒", "保持"),
    ("kind", "💗", "友善"),
    ("long", "📏", "长"),
    ("much", "📦", "许多"),
    ("never", "🚫", "从不"),
    ("only", "1️⃣", "只有"),
    ("own", "🏠", "自己的"),
    ("pick", "🌸", "挑选"),
    ("shall", "📜", "将要"),
    ("show", "👀", "展示"),
    ("start", "🏁", "开始"),
    ("today", "📅", "今天"),
    ("together", "🤝", "一起"),
    ("try", "💪", "尝试"),
    ("warm", "☀️", "温暖"),
    ("also", "➕", "也"),
    ("answer", "✅", "答案"),
    ("city", "🏙️", "城市"),
    ("famous", "⭐", "著名"),
    ("group", "👥", "小组"),
    ("listen", "👂", "听"),
]

# 30 heart words · Gr 4
_SIGHT_4 = [
    ("measure", "📏", "测量"),
    ("question", "❓", "问题"),
    ("special", "✨", "特别"),
    ("surprise", "🎁", "惊喜"),
    ("though", "🤔", "虽然"),
    ("young", "🧒", "年轻"),
    ("among", "👥", "在…之中"),
    ("caught", "🎣", "抓住"),
    ("country", "🗺️", "国家"),
    ("early", "🌅", "早"),
    ("example", "💡", "例子"),
    ("field", "🌾", "田野"),
    ("forest", "🌲", "森林"),
    ("history", "📜", "历史"),
    ("island", "🏝️", "岛屿"),
    ("language", "🗣️", "语言"),
    ("notice", "👀", "注意到"),
    ("object", "📦", "物体"),
    ("paragraph", "📄", "段落"),
    ("passage", "📖", "段落；通道"),
    ("planet", "🪐", "行星"),
    ("problem", "🧩", "问题"),
    ("region", "🗺️", "地区"),
    ("remember", "🧠", "记得"),
    ("science", "🔬", "科学"),
    ("sentence", "📝", "句子"),
    ("suppose", "💭", "猜想"),
    ("therefore", "➡️", "因此"),
    ("vegetable", "🥕", "蔬菜"),
    ("whether", "🤷", "是否"),
]

# 30 multisyllable · Gr 3
_MULTISYLLABLE = [
    ("animal", "🐾", "动物"),
    ("basket", "🧺", "篮子"),
    ("candle", "🕯️", "蜡烛"),
    ("carrot", "🥕", "胡萝卜"),
    ("dinner", "🍽️", "晚餐"),
    ("finger", "☝️", "手指"),
    ("happy", "😊", "快乐"),
    ("kitten", "🐱", "小猫"),
    ("lemon", "🍋", "柠檬"),
    ("magic", "✨", "魔法"),
    ("monkey", "🐒", "猴子"),
    ("number", "🔢", "数字"),
    ("pencil", "✏️", "铅笔"),
    ("pocket", "👖", "口袋"),
    ("pumpkin", "🎃", "南瓜"),
    ("rabbit", "🐰", "兔子"),
    ("rocket", "🚀", "火箭"),
    ("silver", "🥈", "银色"),
    ("trumpet", "🎺", "小号"),
    ("window", "🪟", "窗户"),
    ("blanket", "🛏️", "毯子"),
    ("golden", "🏅", "金色"),
    ("happen", "⚡", "发生"),
    ("jacket", "🧥", "夹克"),
    ("lesson", "📚", "课"),
    ("market", "🏪", "市场"),
    ("napkin", "🧻", "餐巾"),
    ("picnic", "🧺", "野餐"),
    ("ticket", "🎫", "票"),
    ("travel", "✈️", "旅行"),
]

# 22 prefix & suffix · Gr 4
_AFFIX = [
    ("preview", "👀", "预览"),
    ("reread", "📖", "重读"),
    ("subway", "🚇", "地铁"),
    ("unhappy", "😢", "不开心"),
    ("refill", "🔄", "再装满"),
    ("rewrite", "✍️", "重写"),
    ("hopeful", "🌈", "有希望"),
    ("joyful", "😄", "快乐"),
    ("quickly", "⚡", "快速地"),
    ("slowly", "🐢", "慢慢地"),
    ("baking", "🥧", "烘焙"),
    ("running", "🏃", "跑步"),
    ("jumped", "🦘", "跳了"),
    ("playing", "🎮", "玩耍"),
    ("kindness", "💗", "善良"),
    ("darkness", "🌑", "黑暗"),
    ("helpful", "🤝", "有帮助"),
    ("careful", "⚠️", "小心"),
    ("fearless", "🦁", "无畏"),
    ("powerful", "💪", "强大"),
    ("weakness", "🪶", "弱点"),
    ("movement", "💃", "运动"),
]

# 30 basic vocabulary · Gr 3–4
_BASIC_34 = [
    ("ocean", "🌊", "海洋", 5, "3"),
    ("mountain", "⛰️", "山", 5, "3"),
    ("desert", "🏜️", "沙漠", 5, "3"),
    ("hurricane", "🌀", "飓风", 6, "3"),
    ("dinosaur", "🦕", "恐龙", 5, "3"),
    ("cafeteria", "🍽️", "食堂", 6, "3"),
    ("museum", "🏛️", "博物馆", 6, "3"),
    ("hospital", "🏥", "医院", 6, "3"),
    ("rectangle", "▭", "长方形", 5, "3"),
    ("triangle", "🔺", "三角形", 5, "3"),
    ("alphabet", "🔤", "字母表", 5, "3"),
    ("dictionary", "📕", "词典", 6, "3"),
    ("autumn", "🍁", "秋天", 5, "3"),
    ("calendar", "📆", "日历", 5, "3"),
    ("compass", "🧭", "指南针", 5, "3"),
    ("volcano", "🌋", "火山", 6, "4"),
    ("tornado", "🌪️", "龙卷风", 6, "4"),
    ("galaxy", "🌌", "星系", 6, "4"),
    ("microscope", "🔬", "显微镜", 6, "4"),
    ("telescope", "🔭", "望远镜", 6, "4"),
    ("encyclopedia", "📚", "百科全书", 7, "4"),
    ("peninsula", "🏖️", "半岛", 6, "4"),
    ("equator", "🌍", "赤道", 6, "4"),
    ("geography", "🗺️", "地理", 6, "4"),
    ("civilization", "🏛️", "文明", 7, "4"),
    ("electricity", "⚡", "电", 6, "4"),
    ("temperature", "🌡️", "温度", 6, "4"),
    ("experiment", "🧪", "实验", 6, "4"),
    ("multiplication", "✖️", "乘法", 6, "4"),
    ("division", "➗", "除法", 6, "4"),
]

# 130 Minecraft · topic deck (grade 2–3 reading)
_MINECRAFT = [
    # blocks & materials
    ("grass", "🟩", "草方块", 3, "2"),
    ("dirt", "🟫", "泥土", 3, "2"),
    ("stone", "🪨", "石头", 3, "2"),
    ("sand", "🏖️", "沙子", 3, "2"),
    ("gravel", "⚪", "沙砾", 3, "2"),
    ("clay", "🧱", "黏土", 3, "2"),
    ("brick", "🧱", "砖块", 3, "2"),
    ("obsidian", "⬛", "黑曜石", 4, "3"),
    ("bedrock", "🪨", "基岩", 4, "3"),
    ("cobblestone", "🪨", "圆石", 4, "3"),
    ("plank", "🪵", "木板", 3, "2"),
    ("ore", "💎", "矿石", 3, "2"),
    ("emerald", "💚", "绿宝石", 3, "2"),
    ("redstone", "🔴", "红石", 4, "3"),
    ("copper", "🟠", "铜", 3, "2"),
    ("coal", "⚫", "煤炭", 3, "2"),
    ("iron", "⚙️", "铁", 3, "2"),
    ("gold", "🥇", "金", 3, "2"),
    ("diamond", "💎", "钻石", 3, "2"),
    ("netherite", "🟣", "下界合金", 5, "3"),
    ("lava", "🌋", "熔岩", 3, "2"),
    ("netherrack", "🟥", "下界岩", 4, "3"),
    ("glowstone", "💡", "荧石", 4, "3"),
    ("wool", "🐑", "羊毛", 3, "2"),
    ("glass", "🪟", "玻璃", 3, "2"),
    ("ice", "🧊", "冰", 3, "2"),
    ("snow", "❄️", "雪", 3, "2"),
    ("wood", "🪵", "木头", 3, "2"),
    ("tnt", "💥", "TNT", 3, "2"),
    ("sponge", "🧽", "海绵", 3, "2"),
    ("quartz", "⬜", "石英", 3, "2"),
    ("lapis", "🔵", "青金石", 3, "2"),
    ("prismarine", "🔷", "海晶石", 5, "3"),
    ("sculk", "🟦", "幽匿块", 4, "3"),
    # mobs
    ("zombie", "🧟", "僵尸", 3, "2"),
    ("skeleton", "💀", "骷髅", 3, "2"),
    ("spider", "🕷️", "蜘蛛", 3, "2"),
    ("creeper", "💚", "苦力怕", 3, "2"),
    ("enderman", "🟣", "末影人", 4, "3"),
    ("villager", "👨‍🌾", "村民", 3, "2"),
    ("piglin", "🐷", "猪灵", 3, "2"),
    ("ghast", "👻", "恶魂", 3, "2"),
    ("blaze", "🔥", "烈焰人", 3, "2"),
    ("slime", "🟢", "史莱姆", 3, "2"),
    ("wolf", "🐺", "狼", 3, "2"),
    ("chicken", "🐔", "鸡", 3, "2"),
    ("dragon", "🐉", "龙", 3, "2"),
    ("wither", "💀", "凋灵", 3, "2"),
    ("guardian", "🐟", "守卫者", 4, "3"),
    ("phantom", "👻", "幻翼", 3, "2"),
    ("drowned", "🧟", "溺尸", 3, "2"),
    ("husk", "🧟", "尸壳", 3, "2"),
    ("stray", "💀", "流浪者", 3, "2"),
    ("ocelot", "🐱", "豹猫", 4, "3"),
    ("panda", "🐼", "熊猫", 3, "2"),
    ("axolotl", "🦎", "美西螈", 4, "3"),
    ("warden", "👹", "监守者", 3, "2"),
    ("allay", "✨", "悦灵", 3, "2"),
    ("dolphin", "🐬", "海豚", 3, "2"),
    ("squid", "🦑", "鱿鱼", 3, "2"),
    ("turtle", "🐢", "海龟", 3, "2"),
    ("llama", "🦙", "羊驼", 3, "2"),
    ("camel", "🐫", "骆驼", 3, "2"),
    ("sniffer", "🐽", "嗅探兽", 4, "3"),
    # tools & gear
    ("sword", "⚔️", "剑", 3, "2"),
    ("pickaxe", "⛏️", "镐", 3, "2"),
    ("axe", "🪓", "斧", 3, "2"),
    ("shovel", "🔧", "锹", 3, "2"),
    ("hoe", "🌾", "锄", 3, "2"),
    ("bow", "🏹", "弓", 3, "2"),
    ("arrow", "🏹", "箭", 3, "2"),
    ("shield", "🛡️", "盾", 3, "2"),
    ("armor", "🛡️", "盔甲", 3, "2"),
    ("helmet", "⛑️", "头盔", 3, "2"),
    ("chestplate", "🦺", "胸甲", 4, "3"),
    ("leggings", "👖", "护腿", 4, "3"),
    ("boots", "👢", "靴子", 3, "2"),
    ("torch", "🔦", "火把", 3, "2"),
    ("lantern", "🏮", "灯笼", 3, "2"),
    ("bucket", "🪣", "桶", 3, "2"),
    ("flint", "🪨", "燧石", 3, "2"),
    ("shears", "✂️", "剪刀", 3, "2"),
    ("saddle", "🪑", "鞍", 3, "2"),
    ("lead", "🪢", "拴绳", 3, "2"),
    ("minecart", "🛤️", "矿车", 4, "3"),
    # blocks & machines
    ("chest", "📦", "箱子", 3, "2"),
    ("furnace", "🔥", "熔炉", 3, "2"),
    ("anvil", "🔨", "铁砧", 3, "2"),
    ("piston", "🔩", "活塞", 3, "2"),
    ("dispenser", "📤", "发射器", 4, "3"),
    ("hopper", "⬇️", "漏斗", 3, "2"),
    ("lever", "🎚️", "拉杆", 3, "2"),
    ("button", "🔘", "按钮", 3, "2"),
    ("rail", "🛤️", "铁轨", 3, "2"),
    ("ladder", "🪜", "梯子", 3, "2"),
    ("fence", "🚧", "栅栏", 3, "2"),
    ("gate", "🚪", "门", 3, "2"),
    ("trapdoor", "🪤", "活板门", 4, "3"),
    ("beacon", "📡", "信标", 3, "2"),
    ("bookshelf", "📚", "书架", 4, "3"),
    ("portal", "🌀", "传送门", 3, "2"),
    ("enchanting", "✨", "附魔", 4, "3"),
    # places
    ("village", "🏘️", "村庄", 3, "2"),
    ("temple", "🏛️", "神庙", 3, "2"),
    ("fortress", "🏰", "要塞", 4, "3"),
    ("dungeon", "⛓️", "地牢", 3, "2"),
    ("mineshaft", "⛏️", "矿井", 4, "3"),
    ("nether", "🔥", "下界", 3, "2"),
    ("overworld", "🌍", "主世界", 4, "3"),
    ("biome", "🗺️", "生物群系", 4, "3"),
    ("cave", "🕳️", "洞穴", 3, "2"),
    ("jungle", "🌴", "丛林", 3, "2"),
    ("swamp", "🐸", "沼泽", 3, "2"),
    ("ravine", "🏞️", "峡谷", 4, "3"),
    ("stronghold", "🏰", "要塞", 5, "3"),
    # gameplay
    ("craft", "🛠️", "合成", 3, "2"),
    ("mine", "⛏️", "挖矿", 3, "2"),
    ("build", "🏗️", "建造", 3, "2"),
    ("spawn", "✨", "出生", 3, "2"),
    ("world", "🌍", "世界", 3, "2"),
    ("seed", "🌱", "种子码", 3, "2"),
    ("player", "🧑", "玩家", 3, "2"),
    ("mob", "👾", "生物", 3, "2"),
    ("item", "📦", "物品", 3, "2"),
    ("inventory", "🎒", "背包", 4, "3"),
    ("hotbar", "📊", "快捷栏", 4, "3"),
    ("enchant", "✨", "附魔", 4, "3"),
    ("enchantment", "📜", "附魔", 5, "3"),
    ("survival", "❤️", "生存模式", 4, "3"),
    ("creative", "🎨", "创造模式", 4, "3"),
    ("farming", "🌾", "种田", 3, "2"),
    ("mining", "⛏️", "采矿", 3, "2"),
    ("trading", "🤝", "交易", 4, "3"),
    ("brewing", "🧪", "酿造", 4, "3"),
    ("smelting", "🔥", "冶炼", 4, "3"),
    ("crafting", "🔨", "制作", 4, "3"),
    ("respawn", "🔄", "重生", 4, "3"),
    ("harvest", "🌾", "收获", 3, "2"),
    ("explore", "🧭", "探索", 3, "2"),
    ("tame", "🐾", "驯服", 3, "2"),
    ("breed", "🐣", "繁殖", 3, "2"),
    ("smelt", "🔥", "熔炼", 3, "2"),
    ("loot", "💰", "战利品", 3, "2"),
    ("stack", "📚", "堆叠", 3, "2"),
    ("health", "❤️", "生命值", 3, "2"),
    ("hunger", "🍖", "饥饿值", 3, "2"),
    ("experience", "⭐", "经验", 4, "3"),
    ("adventure", "🗺️", "冒险", 4, "3"),
    # food & plants
    ("stew", "🍲", "炖汤", 3, "2"),
    ("honey", "🍯", "蜂蜜", 3, "2"),
    ("steak", "🥩", "牛排", 3, "2"),
    ("melon", "🍈", "西瓜", 3, "2"),
    ("berry", "🫐", "浆果", 3, "2"),
    ("mushroom", "🍄", "蘑菇", 3, "2"),
    ("sapling", "🌱", "树苗", 4, "3"),
    ("kelp", "🌿", "海带", 3, "2"),
    ("coral", "🪸", "珊瑚", 3, "2"),
    ("potion", "🧪", "药水", 3, "2"),
    # redstone & end
    ("repeater", "🔁", "中继器", 4, "3"),
    ("comparator", "📶", "比较器", 5, "3"),
    ("observer", "👁️", "侦测器", 4, "3"),
    ("pearl", "🟣", "珍珠", 3, "2"),
    ("crystal", "🔮", "水晶", 3, "2"),
    ("shulker", "📦", "潜影贝", 4, "3"),
    ("chorus", "🌸", "紫颂果", 4, "3"),
]


def build_base_rows():
    rows = []
    for w, e, zh in _CVC:
        rows.append(_r(w, e, zh, "cvc", 2, "CVC", "K"))
    for w, e, zh in _BLEND:
        rows.append(_r(w, e, zh, "phonics", 4, "Blend", "1"))
    for w, e, zh in _DIGRAPH:
        rows.append(_r(w, e, zh, "phonics", 4, "Digraph", "1"))
    for w, e, zh in _SILENT_E:
        rows.append(_r(w, e, zh, "phonics", 4, "Silent e", "1"))
    for w, e, zh in _VOWEL_TEAM:
        rows.append(_r(w, e, zh, "phonics", 4, "Vowel team", "1"))
    for w, e, zh in _R_CONTROLLED:
        rows.append(_r(w, e, zh, "phonics", 5, "R-controlled", "2"))
    for w, e, zh in _SIGHT_K:
        rows.append(_r(w, e, zh, "sight", 2, "Heart word", "K"))
    for w, e, zh in _SIGHT_1:
        rows.append(_r(w, e, zh, "sight", 3, "Heart word", "1"))
    for w, e, zh in _SIGHT_2:
        rows.append(_r(w, e, zh, "sight", 4, "Heart word", "2"))
    for w, e, zh, d, g in _BASIC:
        rows.append(_r(w, e, zh, "basic", d, "Basic", g))
    for w, e, zh in _SIGHT_3:
        rows.append(_r(w, e, zh, "sight", 5, "Heart word", "3"))
    for w, e, zh in _SIGHT_4:
        rows.append(_r(w, e, zh, "sight", 6, "Heart word", "4"))
    for w, e, zh in _MULTISYLLABLE:
        rows.append(_r(w, e, zh, "phonics", 5, "Multisyllable", "3"))
    for w, e, zh in _AFFIX:
        rows.append(_r(w, e, zh, "phonics", 6, "Prefix & suffix", "4"))
    for w, e, zh, d, g in _BASIC_34:
        rows.append(_r(w, e, zh, "basic", d, "Basic", g))
    for w, e, zh, d, g in _MINECRAFT:
        rows.append(_r(w, e, zh, "minecraft", d, "Minecraft", g))
    return rows


BASE_ROWS = build_base_rows()
