// Auto-generated from words.json — run: node flashcards/tools/sync-embed.mjs
window.__FLASHCARD_WORDS__ = [
  {
    "word": "cat",
    "emoji": "🐱",
    "chinese": "猫",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/kæt/",
    "respelling": "KAT"
  },
  {
    "word": "dog",
    "emoji": "🐶",
    "chinese": "狗",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/dɔːɡ/",
    "respelling": "DAWG"
  },
  {
    "word": "sun",
    "emoji": "☀️",
    "chinese": "太阳",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/sʌn/",
    "respelling": "SUN"
  },
  {
    "word": "bed",
    "emoji": "🛏️",
    "chinese": "床",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/bɛd/",
    "respelling": "BED"
  },
  {
    "word": "pen",
    "emoji": "🖊️",
    "chinese": "笔",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/pɛn/",
    "respelling": "PEN"
  },
  {
    "word": "cup",
    "emoji": "☕",
    "chinese": "杯子",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/kʌp/",
    "respelling": "KUP"
  },
  {
    "word": "map",
    "emoji": "🗺️",
    "chinese": "地图",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/mæp/",
    "respelling": "MAP"
  },
  {
    "word": "hat",
    "emoji": "🎩",
    "chinese": "帽子",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/hæt/",
    "respelling": "HAT"
  },
  {
    "word": "pig",
    "emoji": "🐷",
    "chinese": "猪",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/pɪɡ/",
    "respelling": "PIG"
  },
  {
    "word": "box",
    "emoji": "📦",
    "chinese": "盒子",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/bɑːks/",
    "respelling": "BAHKS"
  },
  {
    "word": "bat",
    "emoji": "🦇",
    "chinese": "蝙蝠",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/bæt/",
    "respelling": "BAT"
  },
  {
    "word": "car",
    "emoji": "🚗",
    "chinese": "车",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/kɑːr/",
    "respelling": "KAR"
  },
  {
    "word": "bus",
    "emoji": "🚌",
    "chinese": "公交车",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/bʌs/",
    "respelling": "BUS"
  },
  {
    "word": "red",
    "emoji": "🔴",
    "chinese": "红色",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/rɛd/",
    "respelling": "RED"
  },
  {
    "word": "run",
    "emoji": "🏃",
    "chinese": "跑",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/rʌn/",
    "respelling": "RUN"
  },
  {
    "word": "sit",
    "emoji": "🪑",
    "chinese": "坐",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/sɪt/",
    "respelling": "SIT"
  },
  {
    "word": "top",
    "emoji": "🔝",
    "chinese": "顶部",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/tɑːp/",
    "respelling": "TAHP"
  },
  {
    "word": "hot",
    "emoji": "🔥",
    "chinese": "热",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/hɑːt/",
    "respelling": "HAHT"
  },
  {
    "word": "big",
    "emoji": "🐘",
    "chinese": "大",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/bɪɡ/",
    "respelling": "BIG"
  },
  {
    "word": "bag",
    "emoji": "🎒",
    "chinese": "包",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/bæɡ/",
    "respelling": "BAG"
  },
  {
    "word": "leg",
    "emoji": "🦵",
    "chinese": "腿",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/lɛɡ/",
    "respelling": "LEG"
  },
  {
    "word": "man",
    "emoji": "👨",
    "chinese": "男人",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/mæn/",
    "respelling": "MAN"
  },
  {
    "word": "fan",
    "emoji": "🌀",
    "chinese": "风扇",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/fæn/",
    "respelling": "FAN"
  },
  {
    "word": "pan",
    "emoji": "🍳",
    "chinese": "锅",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/pæn/",
    "respelling": "PAN"
  },
  {
    "word": "cap",
    "emoji": "🧢",
    "chinese": "帽子",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/kæp/",
    "respelling": "KAP"
  },
  {
    "word": "net",
    "emoji": "🥅",
    "chinese": "网",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/nɛt/",
    "respelling": "NET"
  },
  {
    "word": "jet",
    "emoji": "✈️",
    "chinese": "喷气机",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/dʒɛt/",
    "respelling": "JET"
  },
  {
    "word": "log",
    "emoji": "🪵",
    "chinese": "木头",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/lɔːɡ/",
    "respelling": "LAWG"
  },
  {
    "word": "fox",
    "emoji": "🦊",
    "chinese": "狐狸",
    "type": "cvc",
    "difficulty": 2,
    "wordType": "CVC",
    "gradeLevel": "K",
    "ipa": "/fɑːks/",
    "respelling": "FAHKS"
  },
  {
    "word": "frog",
    "emoji": "🐸",
    "chinese": "青蛙",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/frɔːɡ/",
    "respelling": "FRAHG"
  },
  {
    "word": "flag",
    "emoji": "🏳️",
    "chinese": "旗帜",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/flæɡ/",
    "respelling": "FLAG"
  },
  {
    "word": "plug",
    "emoji": "🔌",
    "chinese": "插头",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/plʌɡ/",
    "respelling": "PLUG"
  },
  {
    "word": "drum",
    "emoji": "🥁",
    "chinese": "鼓",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/drʌm/",
    "respelling": "DRUM"
  },
  {
    "word": "clock",
    "emoji": "🕰️",
    "chinese": "钟",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/klɑːk/",
    "respelling": "KLAHK"
  },
  {
    "word": "truck",
    "emoji": "🚚",
    "chinese": "卡车",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/trʌk/",
    "respelling": "TRUK"
  },
  {
    "word": "plant",
    "emoji": "🌱",
    "chinese": "植物",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/plænt/",
    "respelling": "PLANT"
  },
  {
    "word": "brush",
    "emoji": "🪥",
    "chinese": "刷子",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/brʌʃ/",
    "respelling": "BRUSH"
  },
  {
    "word": "bread",
    "emoji": "🍞",
    "chinese": "面包",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/brɛd/",
    "respelling": "BRED"
  },
  {
    "word": "train",
    "emoji": "🚆",
    "chinese": "火车",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/treɪn/",
    "respelling": "TRAYN"
  },
  {
    "word": "ship",
    "emoji": "🚢",
    "chinese": "船",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/ʃɪp/",
    "respelling": "SHIP"
  },
  {
    "word": "chip",
    "emoji": "🍟",
    "chinese": "薯片",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/tʃɪp/",
    "respelling": "CHIP"
  },
  {
    "word": "fish",
    "emoji": "🐟",
    "chinese": "鱼",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/fɪʃ/",
    "respelling": "FISH"
  },
  {
    "word": "shoe",
    "emoji": "👟",
    "chinese": "鞋",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/ʃuː/",
    "respelling": "SHOO"
  },
  {
    "word": "chair",
    "emoji": "🪑",
    "chinese": "椅子",
    "type": "phonics",
    "difficulty": 5,
    "wordType": "Blend/Digraph",
    "gradeLevel": "1",
    "ipa": "/tʃer/",
    "respelling": "CHAIR"
  },
  {
    "word": "the",
    "emoji": "✨",
    "chinese": "这",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/ðə/",
    "respelling": "thuh"
  },
  {
    "word": "and",
    "emoji": "➕",
    "chinese": "和",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/ænd/",
    "respelling": "AND"
  },
  {
    "word": "you",
    "emoji": "👉",
    "chinese": "你",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/juː/",
    "respelling": "YOO"
  },
  {
    "word": "is",
    "emoji": "✔️",
    "chinese": "是",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/ɪz/",
    "respelling": "IZ"
  },
  {
    "word": "it",
    "emoji": "📌",
    "chinese": "它",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/ɪt/",
    "respelling": "IT"
  },
  {
    "word": "in",
    "emoji": "📥",
    "chinese": "在里面",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/ɪn/",
    "respelling": "IN"
  },
  {
    "word": "on",
    "emoji": "🔛",
    "chinese": "在上面",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/ɑːn/",
    "respelling": "ON"
  },
  {
    "word": "to",
    "emoji": "➡️",
    "chinese": "到",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/tuː/",
    "respelling": "TOO"
  },
  {
    "word": "we",
    "emoji": "👫",
    "chinese": "我们",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/wiː/",
    "respelling": "WEE"
  },
  {
    "word": "go",
    "emoji": "🏃",
    "chinese": "去",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/ɡoʊ/",
    "respelling": "GOH"
  },
  {
    "word": "me",
    "emoji": "🙋",
    "chinese": "我",
    "type": "sight",
    "difficulty": 2,
    "wordType": "Sight",
    "gradeLevel": "K",
    "ipa": "/miː/",
    "respelling": "MEE"
  },
  {
    "word": "they",
    "emoji": "👥",
    "chinese": "他们",
    "type": "sight",
    "difficulty": 3,
    "wordType": "Sight",
    "gradeLevel": "1",
    "ipa": "/ðeɪ/",
    "respelling": "THAY"
  },
  {
    "word": "have",
    "emoji": "🙌",
    "chinese": "有",
    "type": "sight",
    "difficulty": 3,
    "wordType": "Sight",
    "gradeLevel": "1",
    "ipa": "/hæv/",
    "respelling": "HAV"
  },
  {
    "word": "said",
    "emoji": "💬",
    "chinese": "说",
    "type": "sight",
    "difficulty": 3,
    "wordType": "Sight",
    "gradeLevel": "1",
    "ipa": "/sɛd/",
    "respelling": "SED"
  },
  {
    "word": "from",
    "emoji": "➡️",
    "chinese": "从",
    "type": "sight",
    "difficulty": 3,
    "wordType": "Sight",
    "gradeLevel": "1",
    "ipa": "/frʌm/",
    "respelling": "FRUM"
  },
  {
    "word": "what",
    "emoji": "❓",
    "chinese": "什么",
    "type": "sight",
    "difficulty": 3,
    "wordType": "Sight",
    "gradeLevel": "1",
    "ipa": "/wʌt/",
    "respelling": "WUT"
  },
  {
    "word": "when",
    "emoji": "⏰",
    "chinese": "什么时候",
    "type": "sight",
    "difficulty": 3,
    "wordType": "Sight",
    "gradeLevel": "1",
    "ipa": "/wɛn/",
    "respelling": "WEN"
  },
  {
    "word": "where",
    "emoji": "🧭",
    "chinese": "哪里",
    "type": "sight",
    "difficulty": 3,
    "wordType": "Sight",
    "gradeLevel": "1",
    "ipa": "/wer/",
    "respelling": "WAIR"
  },
  {
    "word": "why",
    "emoji": "🤔",
    "chinese": "为什么",
    "type": "sight",
    "difficulty": 3,
    "wordType": "Sight",
    "gradeLevel": "1",
    "ipa": "/waɪ/",
    "respelling": "WY"
  },
  {
    "word": "how",
    "emoji": "⚙️",
    "chinese": "如何",
    "type": "sight",
    "difficulty": 3,
    "wordType": "Sight",
    "gradeLevel": "1",
    "ipa": "/haʊ/",
    "respelling": "HOW"
  },
  {
    "word": "because",
    "emoji": "🤔",
    "chinese": "因为",
    "type": "sight",
    "difficulty": 5,
    "wordType": "Sight",
    "gradeLevel": "2",
    "ipa": "/bɪˈkɔːz/",
    "respelling": "bih-KAWZ"
  },
  {
    "word": "before",
    "emoji": "⏮️",
    "chinese": "之前",
    "type": "sight",
    "difficulty": 5,
    "wordType": "Sight",
    "gradeLevel": "2",
    "ipa": "/bɪˈfɔːr/",
    "respelling": "bee-FOR"
  },
  {
    "word": "after",
    "emoji": "⏭️",
    "chinese": "之后",
    "type": "sight",
    "difficulty": 5,
    "wordType": "Sight",
    "gradeLevel": "2",
    "ipa": "/ˈæftər/",
    "respelling": "AF-ter"
  },
  {
    "word": "again",
    "emoji": "🔁",
    "chinese": "再次",
    "type": "sight",
    "difficulty": 5,
    "wordType": "Sight",
    "gradeLevel": "2",
    "ipa": "/əˈɡɛn/",
    "respelling": "uh-GEN"
  },
  {
    "word": "every",
    "emoji": "📅",
    "chinese": "每个",
    "type": "sight",
    "difficulty": 5,
    "wordType": "Sight",
    "gradeLevel": "2",
    "ipa": "/ˈɛvri/",
    "respelling": "EV-ree"
  },
  {
    "word": "could",
    "emoji": "🤝",
    "chinese": "可以",
    "type": "sight",
    "difficulty": 5,
    "wordType": "Sight",
    "gradeLevel": "2",
    "ipa": "/kʊd/",
    "respelling": "KOOD"
  },
  {
    "word": "should",
    "emoji": "👍",
    "chinese": "应该",
    "type": "sight",
    "difficulty": 5,
    "wordType": "Sight",
    "gradeLevel": "2",
    "ipa": "/ʃʊd/",
    "respelling": "SHOOD"
  },
  {
    "word": "would",
    "emoji": "💭",
    "chinese": "会",
    "type": "sight",
    "difficulty": 5,
    "wordType": "Sight",
    "gradeLevel": "2",
    "ipa": "/wʊd/",
    "respelling": "WOOD"
  },
  {
    "word": "beautiful",
    "emoji": "🌸",
    "chinese": "美丽",
    "type": "advanced",
    "difficulty": 10,
    "wordType": "Advanced",
    "gradeLevel": "10",
    "ipa": "/ˈbjuːtɪfəl/",
    "respelling": "BYOO-tih-full"
  },
  {
    "word": "important",
    "emoji": "⭐",
    "chinese": "重要",
    "type": "advanced",
    "difficulty": 10,
    "wordType": "Advanced",
    "gradeLevel": "10",
    "ipa": "/ɪmˈpɔːrtnt/",
    "respelling": "im-POR-tnt"
  },
  {
    "word": "different",
    "emoji": "🔀",
    "chinese": "不同",
    "type": "advanced",
    "difficulty": 10,
    "wordType": "Advanced",
    "gradeLevel": "10",
    "ipa": "/ˈdɪfrənt/",
    "respelling": "DIFF-runt"
  },
  {
    "word": "information",
    "emoji": "ℹ️",
    "chinese": "信息",
    "type": "advanced",
    "difficulty": 10,
    "wordType": "Advanced",
    "gradeLevel": "10",
    "ipa": "/ˌɪnfərˈmeɪʃən/",
    "respelling": "in-fer-MAY-shun"
  },
  {
    "word": "environment",
    "emoji": "🌍",
    "chinese": "环境",
    "type": "advanced",
    "difficulty": 10,
    "wordType": "Advanced",
    "gradeLevel": "10",
    "ipa": "/ɪnˈvaɪrənmənt/",
    "respelling": "in-VY-run-ment"
  },
  {
    "word": "experience",
    "emoji": "🎢",
    "chinese": "经验",
    "type": "advanced",
    "difficulty": 10,
    "wordType": "Advanced",
    "gradeLevel": "10",
    "ipa": "/ɪkˈspɪriəns/",
    "respelling": "ik-SPEER-ee-uns"
  },
  {
    "word": "education",
    "emoji": "🎓",
    "chinese": "教育",
    "type": "advanced",
    "difficulty": 10,
    "wordType": "Advanced",
    "gradeLevel": "10",
    "ipa": "/ˌɛdʒuˈkeɪʃən/",
    "respelling": "ed-joo-KAY-shun"
  },
  {
    "word": "development",
    "emoji": "📈",
    "chinese": "发展",
    "type": "advanced",
    "difficulty": 10,
    "wordType": "Advanced",
    "gradeLevel": "10",
    "ipa": "/dɪˈvɛləpmənt/",
    "respelling": "dih-VEL-up-munt"
  },
  {
    "word": "apple",
    "emoji": "🍎",
    "chinese": "苹果",
    "type": "basic-food",
    "difficulty": 3,
    "wordType": "Basic · Food",
    "gradeLevel": "K-1",
    "ipa": "/ˈæpəl/",
    "respelling": "AP-ul"
  },
  {
    "word": "banana",
    "emoji": "🍌",
    "chinese": "香蕉",
    "type": "basic-food",
    "difficulty": 3,
    "wordType": "Basic · Food",
    "gradeLevel": "K-1",
    "ipa": "/bəˈnænə/",
    "respelling": "buh-NAN-uh"
  },
  {
    "word": "ball",
    "emoji": "⚽",
    "chinese": "球",
    "type": "basic-things",
    "difficulty": 2,
    "wordType": "Basic · Things",
    "gradeLevel": "K-1",
    "ipa": "/bɔːl/",
    "respelling": "BAWL"
  },
  {
    "word": "tree",
    "emoji": "🌳",
    "chinese": "树",
    "type": "basic-nature",
    "difficulty": 2,
    "wordType": "Basic · Nature",
    "gradeLevel": "K-1",
    "ipa": "/triː/",
    "respelling": "TREE"
  },
  {
    "word": "bird",
    "emoji": "🐦",
    "chinese": "鸟",
    "type": "basic-nature",
    "difficulty": 2,
    "wordType": "Basic · Nature",
    "gradeLevel": "K-1",
    "ipa": "/bɜːrd/",
    "respelling": "BURD"
  },
  {
    "word": "water",
    "emoji": "💧",
    "chinese": "水",
    "type": "basic-food",
    "difficulty": 3,
    "wordType": "Basic · Food",
    "gradeLevel": "K-1",
    "ipa": "/ˈwɔːtər/",
    "respelling": "WAW-ter"
  },
  {
    "word": "milk",
    "emoji": "🥛",
    "chinese": "牛奶",
    "type": "basic-food",
    "difficulty": 2,
    "wordType": "Basic · Food",
    "gradeLevel": "K-1",
    "ipa": "/mɪlk/",
    "respelling": "MILK"
  },
  {
    "word": "book",
    "emoji": "📚",
    "chinese": "书",
    "type": "basic-things",
    "difficulty": 2,
    "wordType": "Basic · Things",
    "gradeLevel": "K-1",
    "ipa": "/bʊk/",
    "respelling": "BOOK"
  },
  {
    "word": "door",
    "emoji": "🚪",
    "chinese": "门",
    "type": "basic-things",
    "difficulty": 2,
    "wordType": "Basic · Things",
    "gradeLevel": "K-1",
    "ipa": "/dɔːr/",
    "respelling": "DOR"
  },
  {
    "word": "house",
    "emoji": "🏠",
    "chinese": "房子",
    "type": "basic-things",
    "difficulty": 3,
    "wordType": "Basic · Things",
    "gradeLevel": "K-1",
    "ipa": "/haʊs/",
    "respelling": "HOWSS"
  },
  {
    "word": "school",
    "emoji": "🏫",
    "chinese": "学校",
    "type": "basic-school",
    "difficulty": 3,
    "wordType": "Basic · School",
    "gradeLevel": "K-1",
    "ipa": "/skuːl/",
    "respelling": "SKOOL"
  },
  {
    "word": "teacher",
    "emoji": "👩‍🏫",
    "chinese": "老师",
    "type": "basic-school",
    "difficulty": 3,
    "wordType": "Basic · School",
    "gradeLevel": "K-1",
    "ipa": "/ˈtiːtʃər/",
    "respelling": "TEE-chur"
  },
  {
    "word": "friend",
    "emoji": "🤝",
    "chinese": "朋友",
    "type": "basic-people",
    "difficulty": 3,
    "wordType": "Basic · People",
    "gradeLevel": "K-1",
    "ipa": "/frɛnd/",
    "respelling": "FREND"
  },
  {
    "word": "family",
    "emoji": "👨‍👩‍👧‍👦",
    "chinese": "家庭",
    "type": "basic-people",
    "difficulty": 3,
    "wordType": "Basic · People",
    "gradeLevel": "K-1",
    "ipa": "/ˈfæməli/",
    "respelling": "FAM-uh-lee"
  },
  {
    "word": "play",
    "emoji": "🎮",
    "chinese": "玩",
    "type": "basic-verbs",
    "difficulty": 2,
    "wordType": "Basic · Verbs",
    "gradeLevel": "K-1",
    "ipa": "/pleɪ/",
    "respelling": "PLAY"
  },
  {
    "word": "eat",
    "emoji": "🍽️",
    "chinese": "吃",
    "type": "basic-verbs",
    "difficulty": 2,
    "wordType": "Basic · Verbs",
    "gradeLevel": "K-1",
    "ipa": "/iːt/",
    "respelling": "EET"
  },
  {
    "word": "sleep",
    "emoji": "😴",
    "chinese": "睡觉",
    "type": "basic-verbs",
    "difficulty": 3,
    "wordType": "Basic · Verbs",
    "gradeLevel": "K-1",
    "ipa": "/sliːp/",
    "respelling": "SLEEP"
  },
  {
    "word": "jump",
    "emoji": "🤾",
    "chinese": "跳",
    "type": "basic-verbs",
    "difficulty": 2,
    "wordType": "Basic · Verbs",
    "gradeLevel": "K-1",
    "ipa": "/dʒʌmp/",
    "respelling": "JUMP"
  },
  {
    "word": "walk",
    "emoji": "🚶",
    "chinese": "走",
    "type": "basic-verbs",
    "difficulty": 2,
    "wordType": "Basic · Verbs",
    "gradeLevel": "K-1",
    "ipa": "/wɔːk/",
    "respelling": "WAWK"
  },
  {
    "word": "read",
    "emoji": "📖",
    "chinese": "读",
    "type": "basic-verbs",
    "difficulty": 2,
    "wordType": "Basic · Verbs",
    "gradeLevel": "K-1",
    "ipa": "/riːd/",
    "respelling": "REED"
  },
  {
    "word": "write",
    "emoji": "✍️",
    "chinese": "写",
    "type": "basic-verbs",
    "difficulty": 3,
    "wordType": "Basic · Verbs",
    "gradeLevel": "K-1",
    "ipa": "/raɪt/",
    "respelling": "RYTE"
  },
  {
    "word": "draw",
    "emoji": "🎨",
    "chinese": "画",
    "type": "basic-verbs",
    "difficulty": 2,
    "wordType": "Basic · Verbs",
    "gradeLevel": "K-1",
    "ipa": "/drɔː/",
    "respelling": "DRAW"
  }
]
