// Flashcard word list (source of truth). Edit tools/word_list_data.py, then:
//   python3 flashcards/tools/build_words_embed.py
//   python3 flashcards/tools/merge-pronunciations.py
window.__FLASHCARD_WORDS__ = [
  {"word": "cat", "emoji": "🐱", "chinese": "猫", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kæt/", "respelling": "KAT"},
  {"word": "dog", "emoji": "🐶", "chinese": "狗", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dɔːɡ/", "respelling": "DAWG"},
  {"word": "sun", "emoji": "☀️", "chinese": "太阳", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sʌn/", "respelling": "SUN"},
  {"word": "bed", "emoji": "🛏️", "chinese": "床", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bɛd/", "respelling": "BED"},
  {"word": "pen", "emoji": "✏️", "chinese": "笔", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɛn/", "respelling": "PEN"},
  {"word": "cup", "emoji": "🥤", "chinese": "杯子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kʌp/", "respelling": "KUP"},
  {"word": "map", "emoji": "🗺️", "chinese": "地图", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mæp/", "respelling": "MAP"},
  {"word": "hat", "emoji": "🎩", "chinese": "帽子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hæt/", "respelling": "HAT"},
  {"word": "pig", "emoji": "🐷", "chinese": "猪", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɪɡ/", "respelling": "PIG"},
  {"word": "bat", "emoji": "🏏", "chinese": "球棒", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bæt/", "respelling": "BAT"},
  {"word": "bus", "emoji": "🚌", "chinese": "巴士", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bʌs/", "respelling": "BUS"},
  {"word": "red", "emoji": "🔴", "chinese": "红色", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rɛd/", "respelling": "RED"},
  {"word": "run", "emoji": "🏃", "chinese": "跑", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rʌn/", "respelling": "RUN"},
  {"word": "sit", "emoji": "🧘", "chinese": "坐", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sɪt/", "respelling": "SIT"},
  {"word": "top", "emoji": "🔝", "chinese": "顶", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tɑːp/", "respelling": "TAHP"},
  {"word": "hot", "emoji": "🌶️", "chinese": "热", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hɑːt/", "respelling": "HAHT"},
  {"word": "big", "emoji": "⬆️", "chinese": "大", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bɪɡ/", "respelling": "BIG"},
  {"word": "bag", "emoji": "👜", "chinese": "包", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bæɡ/", "respelling": "BAG"},
  {"word": "leg", "emoji": "🦵", "chinese": "腿", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/lɛɡ/", "respelling": "LEG"},
  {"word": "man", "emoji": "👨", "chinese": "男人", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mæn/", "respelling": "MAN"},
  {"word": "fan", "emoji": "🪭", "chinese": "扇子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fæn/", "respelling": "FAN"},
  {"word": "pan", "emoji": "🍳", "chinese": "平底锅", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pæn/", "respelling": "PAN"},
  {"word": "cap", "emoji": "🧢", "chinese": "鸭舌帽", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kæp/", "respelling": "KAP"},
  {"word": "net", "emoji": "🥅", "chinese": "网", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/nɛt/", "respelling": "NET"},
  {"word": "jet", "emoji": "✈️", "chinese": "喷气机", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dʒɛt/", "respelling": "JET"},
  {"word": "log", "emoji": "🪵", "chinese": "原木", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/lɔːɡ/", "respelling": "LAWG"},
  {"word": "van", "emoji": "🚐", "chinese": "货车", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/væn/", "respelling": "VAN"},
  {"word": "web", "emoji": "🕸️", "chinese": "网", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/wɛb/", "respelling": "WEB"},
  {"word": "wig", "emoji": "💇", "chinese": "假发", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/wɪɡ/", "respelling": "WIG"},
  {"word": "zip", "emoji": "🤐", "chinese": "拉链", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/zɪp/", "respelling": "ZIP"},
  {"word": "box", "emoji": "📦", "chinese": "盒子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bɑːks/", "respelling": "BAHKS"},
  {"word": "fox", "emoji": "🦊", "chinese": "狐狸", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fɑːks/", "respelling": "FAHKS"},
  {"word": "six", "emoji": "6️⃣", "chinese": "六", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sɪks/", "respelling": "SIKS"},
  {"word": "rug", "emoji": "🟫", "chinese": "地毯", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rʌɡ/", "respelling": "RUG"},
  {"word": "tug", "emoji": "🪢", "chinese": "拽", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tʌɡ/", "respelling": "TUG"},
  {"word": "mug", "emoji": "☕", "chinese": "马克杯", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mʌɡ/", "respelling": "MUG"},
  {"word": "bun", "emoji": "🥯", "chinese": "小面包", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bʌn/", "respelling": "BUN"},
  {"word": "fun", "emoji": "🎉", "chinese": "好玩", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fʌn/", "respelling": "FUN"},
  {"word": "hen", "emoji": "🐔", "chinese": "母鸡", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hɛn/", "respelling": "HEN"},
  {"word": "cob", "emoji": "🌽", "chinese": "玉米棒", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kɑːb/", "respelling": "KAHB"},
  {"word": "flag", "emoji": "🚩", "chinese": "旗", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/flæɡ/", "respelling": "FLAG"},
  {"word": "plug", "emoji": "🔌", "chinese": "塞子", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/plʌɡ/", "respelling": "PLUG"},
  {"word": "drum", "emoji": "🥁", "chinese": "鼓", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/drʌm/", "respelling": "DRUM"},
  {"word": "frog", "emoji": "🐸", "chinese": "青蛙", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/frɔːɡ/", "respelling": "FRAHG"},
  {"word": "plan", "emoji": "📋", "chinese": "计划", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/plæn/", "respelling": "PLAN"},
  {"word": "block", "emoji": "🧱", "chinese": "积木", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/blɑːk/", "respelling": "BLAHK"},
  {"word": "club", "emoji": "♣️", "chinese": "俱乐部", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/klʌb/", "respelling": "KLUB"},
  {"word": "crop", "emoji": "🌾", "chinese": "庄稼", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/krɑːp/", "respelling": "KRAHP"},
  {"word": "star", "emoji": "⭐", "chinese": "星星", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/stɑːr/", "respelling": "STAR"},
  {"word": "stop", "emoji": "🛑", "chinese": "停", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/stɑːp/", "respelling": "STOP"},
  {"word": "swim", "emoji": "🏊", "chinese": "游泳", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/swɪm/", "respelling": "SWIM"},
  {"word": "sled", "emoji": "🛷", "chinese": "雪橇", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/slɛd/", "respelling": "SLED"},
  {"word": "trim", "emoji": "✂️", "chinese": "修剪", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/trɪm/", "respelling": "TRIM"},
  {"word": "trap", "emoji": "🪤", "chinese": "陷阱", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/træp/", "respelling": "TRAP"},
  {"word": "crib", "emoji": "🛏️", "chinese": "婴儿床", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/krɪb/", "respelling": "KRIB"},
  {"word": "grab", "emoji": "✊", "chinese": "抓", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/ɡræb/", "respelling": "GRAB"},
  {"word": "glad", "emoji": "😊", "chinese": "高兴", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/ɡlæd/", "respelling": "GLAD"},
  {"word": "flip", "emoji": "🤸", "chinese": "翻", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/flɪp/", "respelling": "FLIP"},
  {"word": "clip", "emoji": "📎", "chinese": "夹子", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/klɪp/", "respelling": "KLIP"},
  {"word": "drop", "emoji": "💧", "chinese": "滴", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/drɑːp/", "respelling": "DRAHP"},
  {"word": "ship", "emoji": "🚢", "chinese": "船", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ʃɪp/", "respelling": "SHIP"},
  {"word": "chip", "emoji": "🥔", "chinese": "薯片", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/tʃɪp/", "respelling": "CHIP"},
  {"word": "fish", "emoji": "🐟", "chinese": "鱼", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/fɪʃ/", "respelling": "FISH"},
  {"word": "shoe", "emoji": "👟", "chinese": "鞋", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ʃuː/", "respelling": "SHOO"},
  {"word": "chat", "emoji": "💬", "chinese": "聊天", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/tʃæt/", "respelling": "CHAT"},
  {"word": "shop", "emoji": "🛒", "chinese": "商店", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ʃɑːp/", "respelling": "SHOP"},
  {"word": "shell", "emoji": "🐚", "chinese": "贝壳", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ʃɛl/", "respelling": "SHEL"},
  {"word": "dish", "emoji": "🍽️", "chinese": "盘子", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/dɪʃ/", "respelling": "DISH"},
  {"word": "wish", "emoji": "🌠", "chinese": "愿望", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/wɪʃ/", "respelling": "WISH"},
  {"word": "chop", "emoji": "🔪", "chinese": "砍", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/tʃɑːp/", "respelling": "CHOP"},
  {"word": "chin", "emoji": "🙂", "chinese": "下巴", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/tʃɪn/", "respelling": "CHIN"},
  {"word": "math", "emoji": "➕", "chinese": "数学", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/mæθ/", "respelling": "MATH"},
  {"word": "path", "emoji": "🛤️", "chinese": "小路", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/pæθ/", "respelling": "PATH"},
  {"word": "bath", "emoji": "🛁", "chinese": "洗澡", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/bæθ/", "respelling": "BATH"},
  {"word": "moth", "emoji": "🦋", "chinese": "蛾", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/mɔːθ/", "respelling": "MAWTH"},
  {"word": "thin", "emoji": "📏", "chinese": "薄", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/θɪn/", "respelling": "THIN"},
  {"word": "that", "emoji": "👉", "chinese": "那", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ðæt/", "respelling": "THAT"},
  {"word": "then", "emoji": "⏭️", "chinese": "然后", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ðɛn/", "respelling": "THEN"},
  {"word": "when", "emoji": "⏰", "chinese": "何时", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/wɛn/", "respelling": "WEN"},
  {"word": "whale", "emoji": "🐋", "chinese": "鲸", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/weɪl/", "respelling": "WAYL"},
  {"word": "the", "emoji": "✨", "chinese": "这；那个", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ðə/", "respelling": "thuh"},
  {"word": "and", "emoji": "➕", "chinese": "和", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ænd/", "respelling": "AND"},
  {"word": "you", "emoji": "🫵", "chinese": "你", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/juː/", "respelling": "YOO"},
  {"word": "is", "emoji": "ℹ️", "chinese": "是", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɪz/", "respelling": "IZ"},
  {"word": "it", "emoji": "📌", "chinese": "它", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɪt/", "respelling": "IT"},
  {"word": "in", "emoji": "📥", "chinese": "在…里", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɪn/", "respelling": "IN"},
  {"word": "on", "emoji": "📍", "chinese": "在…上", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɑːn/", "respelling": "ON"},
  {"word": "to", "emoji": "➡️", "chinese": "向；到", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/tuː/", "respelling": "TOO"},
  {"word": "we", "emoji": "🧑‍🤝‍🧑", "chinese": "我们", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/wiː/", "respelling": "WEE"},
  {"word": "go", "emoji": "🚶", "chinese": "去", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɡoʊ/", "respelling": "GOH"},
  {"word": "me", "emoji": "🙋", "chinese": "我", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/miː/", "respelling": "MEE"},
  {"word": "they", "emoji": "👥", "chinese": "他们", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/ðeɪ/", "respelling": "THAY"},
  {"word": "have", "emoji": "📦", "chinese": "有", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/hæv/", "respelling": "HAV"},
  {"word": "said", "emoji": "💬", "chinese": "说", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/sɛd/", "respelling": "SED"},
  {"word": "from", "emoji": "📤", "chinese": "从", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/frʌm/", "respelling": "FRUM"},
  {"word": "what", "emoji": "❓", "chinese": "什么", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/wʌt/", "respelling": "WUT"},
  {"word": "when", "emoji": "🕐", "chinese": "何时", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/wɛn/", "respelling": "WEN"},
  {"word": "where", "emoji": "🧭", "chinese": "哪里", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/wer/", "respelling": "WAIR"},
  {"word": "why", "emoji": "🤔", "chinese": "为什么", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/waɪ/", "respelling": "WY"},
  {"word": "how", "emoji": "❔", "chinese": "怎样", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/haʊ/", "respelling": "HOW"},
  {"word": "could", "emoji": "🔮", "chinese": "能", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/kʊd/", "respelling": "KOOD"},
  {"word": "was", "emoji": "⏪", "chinese": "是", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/wʌz/", "respelling": "WUZ"},
  {"word": "are", "emoji": "↔️", "chinese": "是", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/ɑːr/", "respelling": "AR"},
  {"word": "now", "emoji": "📍", "chinese": "现在", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/naʊ/", "respelling": "NOW"},
  {"word": "she", "emoji": "👩", "chinese": "她", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/ʃiː/", "respelling": "SHE"},
  {"word": "apple", "emoji": "🍎", "chinese": "苹果", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/ˈæpəl/", "respelling": "AP-ul"},
  {"word": "banana", "emoji": "🍌", "chinese": "香蕉", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/bəˈnænə/", "respelling": "buh-NAN-uh"},
  {"word": "ball", "emoji": "⚽", "chinese": "球", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/bɔːl/", "respelling": "BAWL"},
  {"word": "tree", "emoji": "🌳", "chinese": "树", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/triː/", "respelling": "TREE"},
  {"word": "bird", "emoji": "🐦", "chinese": "鸟", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/bɜːrd/", "respelling": "BURD"},
  {"word": "water", "emoji": "💧", "chinese": "水", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/ˈwɔːtər/", "respelling": "WAW-ter"},
  {"word": "milk", "emoji": "🥛", "chinese": "牛奶", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/mɪlk/", "respelling": "MILK"},
  {"word": "book", "emoji": "📚", "chinese": "书", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/bʊk/", "respelling": "BOOK"},
  {"word": "door", "emoji": "🚪", "chinese": "门", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/dɔːr/", "respelling": "DOR"},
  {"word": "house", "emoji": "🏠", "chinese": "房子", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/haʊs/", "respelling": "HOWSS"},
  {"word": "school", "emoji": "🏫", "chinese": "学校", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/skuːl/", "respelling": "SKOOL"},
  {"word": "teacher", "emoji": "👩‍🏫", "chinese": "老师", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/ˈtiːtʃər/", "respelling": "TEE-chur"},
  {"word": "friend", "emoji": "🤝", "chinese": "朋友", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/frɛnd/", "respelling": "FREND"},
  {"word": "family", "emoji": "👪", "chinese": "家庭", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/ˈfæməli/", "respelling": "FAM-uh-lee"},
  {"word": "play", "emoji": "🎮", "chinese": "玩", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/pleɪ/", "respelling": "PLAY"}
]
