// Flashcard word list (source of truth). Edit tools/word_list_data.py, then:
//   python3 flashcards/tools/build_words_embed.py
//   python3 flashcards/tools/merge-pronunciations.py
window.__FLASHCARD_WORDS__ = [
  {"word": "cat", "emoji": "🐱", "chinese": "猫", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kæt/", "respelling": "KAT"},
  {"word": "dog", "emoji": "🐶", "chinese": "狗", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dɔːɡ/", "respelling": "DAWG"},
  {"word": "sun", "emoji": "☀️", "chinese": "太阳", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sʌn/", "respelling": "SUN"},
  {"word": "bed", "emoji": "🛏️", "chinese": "床", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bɛd/", "respelling": "BED"},
  {"word": "pen", "emoji": "✏️", "chinese": "笔", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɛn/", "respelling": "PEN"},
  {"word": "cup", "emoji": "🥤", "chinese": "杯子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kʌp/", "respelling": "KUP"},
  {"word": "map", "emoji": "🗺️", "chinese": "地图", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mæp/", "respelling": "MAP"},
  {"word": "hat", "emoji": "🎩", "chinese": "帽子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hæt/", "respelling": "HAT"},
  {"word": "pig", "emoji": "🐷", "chinese": "猪", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɪɡ/", "respelling": "PIG"},
  {"word": "bat", "emoji": "🏏", "chinese": "球棒", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bæt/", "respelling": "BAT"},
  {"word": "bus", "emoji": "🚌", "chinese": "巴士", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bʌs/", "respelling": "BUS"},
  {"word": "red", "emoji": "🔴", "chinese": "红色", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rɛd/", "respelling": "RED"},
  {"word": "run", "emoji": "🏃", "chinese": "跑", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rʌn/", "respelling": "RUN"},
  {"word": "sit", "emoji": "🧘", "chinese": "坐", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sɪt/", "respelling": "SIT"},
  {"word": "top", "emoji": "🔝", "chinese": "顶", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tɑːp/", "respelling": "TAHP"},
  {"word": "hot", "emoji": "🌶️", "chinese": "热", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hɑːt/", "respelling": "HAHT"},
  {"word": "big", "emoji": "⬆️", "chinese": "大", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bɪɡ/", "respelling": "BIG"},
  {"word": "bag", "emoji": "👜", "chinese": "包", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bæɡ/", "respelling": "BAG"},
  {"word": "leg", "emoji": "🦵", "chinese": "腿", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/lɛɡ/", "respelling": "LEG"},
  {"word": "man", "emoji": "👨", "chinese": "男人", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mæn/", "respelling": "MAN"},
  {"word": "fan", "emoji": "🪭", "chinese": "扇子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fæn/", "respelling": "FAN"},
  {"word": "pan", "emoji": "🍳", "chinese": "平底锅", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pæn/", "respelling": "PAN"},
  {"word": "cap", "emoji": "🧢", "chinese": "鸭舌帽", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kæp/", "respelling": "KAP"},
  {"word": "net", "emoji": "🥅", "chinese": "网", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/nɛt/", "respelling": "NET"},
  {"word": "jet", "emoji": "✈️", "chinese": "喷气机", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dʒɛt/", "respelling": "JET"},
  {"word": "log", "emoji": "🪵", "chinese": "原木", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/lɔːɡ/", "respelling": "LAWG"},
  {"word": "van", "emoji": "🚐", "chinese": "货车", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/væn/", "respelling": "VAN"},
  {"word": "web", "emoji": "🕸️", "chinese": "网", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/wɛb/", "respelling": "WEB"},
  {"word": "wig", "emoji": "💇", "chinese": "假发", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/wɪɡ/", "respelling": "WIG"},
  {"word": "zip", "emoji": "🤐", "chinese": "拉链", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/zɪp/", "respelling": "ZIP"},
  {"word": "box", "emoji": "📦", "chinese": "盒子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bɑːks/", "respelling": "BAHKS"},
  {"word": "fox", "emoji": "🦊", "chinese": "狐狸", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fɑːks/", "respelling": "FAHKS"},
  {"word": "six", "emoji": "6️⃣", "chinese": "六", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sɪks/", "respelling": "SIKS"},
  {"word": "rug", "emoji": "🟫", "chinese": "地毯", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rʌɡ/", "respelling": "RUG"},
  {"word": "tug", "emoji": "🪢", "chinese": "拽", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tʌɡ/", "respelling": "TUG"},
  {"word": "mug", "emoji": "☕", "chinese": "马克杯", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mʌɡ/", "respelling": "MUG"},
  {"word": "bun", "emoji": "🥯", "chinese": "小面包", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bʌn/", "respelling": "BUN"},
  {"word": "fun", "emoji": "🎉", "chinese": "好玩", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fʌn/", "respelling": "FUN"},
  {"word": "hen", "emoji": "🐔", "chinese": "母鸡", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hɛn/", "respelling": "HEN"},
  {"word": "cob", "emoji": "🌽", "chinese": "玉米棒", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kɑːb/", "respelling": "KAHB"},
  {"word": "dad", "emoji": "👨", "chinese": "爸爸", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dæd/", "respelling": "DAD"},
  {"word": "mom", "emoji": "👩", "chinese": "妈妈", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mɑːm/", "respelling": "MAHM"},
  {"word": "car", "emoji": "🚗", "chinese": "汽车", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kɑːr/", "respelling": "KAR"},
  {"word": "ant", "emoji": "🐜", "chinese": "蚂蚁", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/ænt/", "respelling": "ANT"},
  {"word": "tub", "emoji": "🛁", "chinese": "浴缸", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tʌb/", "respelling": "TUB"},
  {"word": "hug", "emoji": "🤗", "chinese": "抱", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hʌɡ/", "respelling": "HUG"},
  {"word": "pet", "emoji": "🐾", "chinese": "宠物", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɛt/", "respelling": "PET"},
  {"word": "jam", "emoji": "🍓", "chinese": "果酱", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dʒæm/", "respelling": "JAM"},
  {"word": "mat", "emoji": "🧶", "chinese": "垫子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mæt/", "respelling": "MAT"},
  {"word": "sat", "emoji": "🪑", "chinese": "坐", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sæt/", "respelling": "SAT"},
  {"word": "rat", "emoji": "🐀", "chinese": "老鼠", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/ræt/", "respelling": "RAT"},
  {"word": "fat", "emoji": "🍔", "chinese": "胖", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fæt/", "respelling": "FAT"},
  {"word": "pat", "emoji": "👋", "chinese": "拍", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pæt/", "respelling": "PAT"},
  {"word": "wag", "emoji": "🐕", "chinese": "摇尾", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/wæɡ/", "respelling": "WAG"},
  {"word": "tag", "emoji": "🏷️", "chinese": "标签", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tæɡ/", "respelling": "TAG"},
  {"word": "ham", "emoji": "🍖", "chinese": "火腿", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hæm/", "respelling": "HAM"},
  {"word": "ram", "emoji": "🐏", "chinese": "公羊", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/ræm/", "respelling": "RAM"},
  {"word": "tab", "emoji": "📑", "chinese": "标签页", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tæb/", "respelling": "TAB"},
  {"word": "sad", "emoji": "😢", "chinese": "难过", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sæd/", "respelling": "SAD"},
  {"word": "mad", "emoji": "😠", "chinese": "生气", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mæd/", "respelling": "MAD"},
  {"word": "pad", "emoji": "📝", "chinese": "便签本", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pæd/", "respelling": "PAD"},
  {"word": "lap", "emoji": "🦵", "chinese": "大腿", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/læp/", "respelling": "LAP"},
  {"word": "tap", "emoji": "🚰", "chinese": "轻敲", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tæp/", "respelling": "TAP"},
  {"word": "nap", "emoji": "😴", "chinese": "小睡", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/næp/", "respelling": "NAP"},
  {"word": "gap", "emoji": "↔️", "chinese": "缝隙", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/ɡæp/", "respelling": "GAP"},
  {"word": "sap", "emoji": "🌲", "chinese": "树液", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sæp/", "respelling": "SAP"},
  {"word": "yak", "emoji": "🐂", "chinese": "牦牛", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/jæk/", "respelling": "YAK"},
  {"word": "vat", "emoji": "🛢️", "chinese": "大桶", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/væt/", "respelling": "VAT"},
  {"word": "bet", "emoji": "🎲", "chinese": "打赌", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bɛt/", "respelling": "BET"},
  {"word": "let", "emoji": "✋", "chinese": "让", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/lɛt/", "respelling": "LET"},
  {"word": "ten", "emoji": "🔟", "chinese": "十", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tɛn/", "respelling": "TEN"},
  {"word": "men", "emoji": "👨", "chinese": "男人们", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mɛn/", "respelling": "MEN"},
  {"word": "wet", "emoji": "💧", "chinese": "湿", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/wɛt/", "respelling": "WET"},
  {"word": "set", "emoji": "📦", "chinese": "一套", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sɛt/", "respelling": "SET"},
  {"word": "met", "emoji": "🤝", "chinese": "遇见", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mɛt/", "respelling": "MET"},
  {"word": "vet", "emoji": "👨‍⚕️", "chinese": "兽医", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/vɛt/", "respelling": "VET"},
  {"word": "beg", "emoji": "🙏", "chinese": "乞求", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bɛɡ/", "respelling": "BEG"},
  {"word": "peg", "emoji": "📌", "chinese": "木钉", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɛɡ/", "respelling": "PEG"},
  {"word": "den", "emoji": "🦁", "chinese": "兽穴", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dɛn/", "respelling": "DEN"},
  {"word": "bit", "emoji": "🔩", "chinese": "一点", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bɪt/", "respelling": "BIT"},
  {"word": "hit", "emoji": "👊", "chinese": "打", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hɪt/", "respelling": "HIT"},
  {"word": "pit", "emoji": "🕳️", "chinese": "坑", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɪt/", "respelling": "PIT"},
  {"word": "fit", "emoji": "✅", "chinese": "合适", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fɪt/", "respelling": "FIT"},
  {"word": "kit", "emoji": "🧰", "chinese": "工具包", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kɪt/", "respelling": "KIT"},
  {"word": "dig", "emoji": "⛏️", "chinese": "挖", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dɪɡ/", "respelling": "DIG"},
  {"word": "fin", "emoji": "🦈", "chinese": "鱼鳍", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fɪn/", "respelling": "FIN"},
  {"word": "pin", "emoji": "📍", "chinese": "别针", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɪn/", "respelling": "PIN"},
  {"word": "tin", "emoji": "🥫", "chinese": "锡", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tɪn/", "respelling": "TIN"},
  {"word": "bin", "emoji": "🗑️", "chinese": "箱子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bɪn/", "respelling": "BIN"},
  {"word": "win", "emoji": "🏆", "chinese": "赢", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/wɪn/", "respelling": "WIN"},
  {"word": "rip", "emoji": "📄", "chinese": "撕", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rɪp/", "respelling": "RIP"},
  {"word": "lip", "emoji": "👄", "chinese": "嘴唇", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/lɪp/", "respelling": "LIP"},
  {"word": "hip", "emoji": "🦴", "chinese": "髋", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hɪp/", "respelling": "HIP"},
  {"word": "dip", "emoji": "🫕", "chinese": "蘸", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dɪp/", "respelling": "DIP"},
  {"word": "tip", "emoji": "💡", "chinese": "小费；尖端", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/tɪp/", "respelling": "TIP"},
  {"word": "fig", "emoji": "🍇", "chinese": "无花果", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fɪɡ/", "respelling": "FIG"},
  {"word": "rig", "emoji": "🛢️", "chinese": "钻机", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rɪɡ/", "respelling": "RIG"},
  {"word": "sin", "emoji": "😈", "chinese": "罪", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sɪn/", "respelling": "SIN"},
  {"word": "nib", "emoji": "✒️", "chinese": "笔尖", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/nɪb/", "respelling": "NIB"},
  {"word": "pot", "emoji": "🍲", "chinese": "锅", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɑːt/", "respelling": "PAHT"},
  {"word": "hop", "emoji": "🐇", "chinese": "单脚跳", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hɑːp/", "respelling": "HAHP"},
  {"word": "pop", "emoji": "🎈", "chinese": "砰", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɑːp/", "respelling": "PAHP"},
  {"word": "mop", "emoji": "🧹", "chinese": "拖把", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mɑːp/", "respelling": "MAHP"},
  {"word": "dot", "emoji": "⚫", "chinese": "点", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dɑːt/", "respelling": "DAHT"},
  {"word": "lot", "emoji": "🅿️", "chinese": "一块地", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/lɑːt/", "respelling": "LAHT"},
  {"word": "jog", "emoji": "🏃", "chinese": "慢跑", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dʒɑːɡ/", "respelling": "JAWG"},
  {"word": "hog", "emoji": "🐷", "chinese": "猪", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hɑːɡ/", "respelling": "HAWG"},
  {"word": "fog", "emoji": "🌫️", "chinese": "雾", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/fɑːɡ/", "respelling": "FAWG"},
  {"word": "rod", "emoji": "🎣", "chinese": "杆", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rɑːd/", "respelling": "RAHD"},
  {"word": "nod", "emoji": "👍", "chinese": "点头", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/nɑːd/", "respelling": "NAHD"},
  {"word": "pod", "emoji": "🫛", "chinese": "豆荚", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pɑːd/", "respelling": "PAHD"},
  {"word": "cop", "emoji": "👮", "chinese": "警察", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kɑːp/", "respelling": "KAHP"},
  {"word": "sob", "emoji": "😭", "chinese": "抽泣", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sɑːb/", "respelling": "SAHB"},
  {"word": "rob", "emoji": "🦹", "chinese": "抢", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rɑːb/", "respelling": "RAHB"},
  {"word": "bug", "emoji": "🐛", "chinese": "虫子", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bʌɡ/", "respelling": "BUG"},
  {"word": "nut", "emoji": "🥜", "chinese": "坚果", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/nʌt/", "respelling": "NUT"},
  {"word": "hut", "emoji": "🏕️", "chinese": "小屋", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hʌt/", "respelling": "HUT"},
  {"word": "cut", "emoji": "✂️", "chinese": "剪", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kʌt/", "respelling": "KUT"},
  {"word": "mud", "emoji": "🟤", "chinese": "泥", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/mʌd/", "respelling": "MUD"},
  {"word": "cub", "emoji": "🐻", "chinese": "幼崽", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/kʌb/", "respelling": "KUB"},
  {"word": "rub", "emoji": "🤲", "chinese": "揉", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/rʌb/", "respelling": "RUB"},
  {"word": "hum", "emoji": "🎵", "chinese": "哼唱", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/hʌm/", "respelling": "HUM"},
  {"word": "gum", "emoji": "🫧", "chinese": "口香糖", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/ɡʌm/", "respelling": "GUM"},
  {"word": "pup", "emoji": "🐶", "chinese": "小狗", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/pʌp/", "respelling": "PUP"},
  {"word": "sub", "emoji": "🥪", "chinese": "潜艇；三明治", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/sʌb/", "respelling": "SUB"},
  {"word": "bud", "emoji": "🌱", "chinese": "芽", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/bʌd/", "respelling": "BUD"},
  {"word": "jug", "emoji": "🫙", "chinese": "壶", "type": "cvc", "difficulty": 2, "wordType": "CVC", "gradeLevel": "K", "ipa": "/dʒʌɡ/", "respelling": "JUG"},
  {"word": "flag", "emoji": "🚩", "chinese": "旗", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/flæɡ/", "respelling": "FLAG"},
  {"word": "plug", "emoji": "🔌", "chinese": "塞子", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/plʌɡ/", "respelling": "PLUG"},
  {"word": "drum", "emoji": "🥁", "chinese": "鼓", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/drʌm/", "respelling": "DRUM"},
  {"word": "frog", "emoji": "🐸", "chinese": "青蛙", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/frɔːɡ/", "respelling": "FRAHG"},
  {"word": "plan", "emoji": "📋", "chinese": "计划", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/plæn/", "respelling": "PLAN"},
  {"word": "block", "emoji": "🧱", "chinese": "积木", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/blɑːk/", "respelling": "BLAHK"},
  {"word": "club", "emoji": "♣️", "chinese": "俱乐部", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/klʌb/", "respelling": "KLUB"},
  {"word": "crop", "emoji": "🌾", "chinese": "庄稼", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/krɑːp/", "respelling": "KRAHP"},
  {"word": "star", "emoji": "⭐", "chinese": "星星", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/stɑːr/", "respelling": "STAR"},
  {"word": "stop", "emoji": "🛑", "chinese": "停", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/stɑːp/", "respelling": "STOP"},
  {"word": "swim", "emoji": "🏊", "chinese": "游泳", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/swɪm/", "respelling": "SWIM"},
  {"word": "sled", "emoji": "🛷", "chinese": "雪橇", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/slɛd/", "respelling": "SLED"},
  {"word": "trim", "emoji": "✂️", "chinese": "修剪", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/trɪm/", "respelling": "TRIM"},
  {"word": "trap", "emoji": "🪤", "chinese": "陷阱", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/træp/", "respelling": "TRAP"},
  {"word": "crib", "emoji": "🛏️", "chinese": "婴儿床", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/krɪb/", "respelling": "KRIB"},
  {"word": "grab", "emoji": "✊", "chinese": "抓", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/ɡræb/", "respelling": "GRAB"},
  {"word": "glad", "emoji": "😊", "chinese": "高兴", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/ɡlæd/", "respelling": "GLAD"},
  {"word": "flip", "emoji": "🤸", "chinese": "翻", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/flɪp/", "respelling": "FLIP"},
  {"word": "clip", "emoji": "📎", "chinese": "夹子", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/klɪp/", "respelling": "KLIP"},
  {"word": "drop", "emoji": "💧", "chinese": "滴", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/drɑːp/", "respelling": "DRAHP"},
  {"word": "black", "emoji": "⬛", "chinese": "黑色", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/blæk/", "respelling": "BLAK"},
  {"word": "clap", "emoji": "👏", "chinese": "拍手", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/klæp/", "respelling": "KLAP"},
  {"word": "grin", "emoji": "😁", "chinese": "咧嘴笑", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/ɡrɪn/", "respelling": "GRIN"},
  {"word": "grip", "emoji": "✊", "chinese": "紧握", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/ɡrɪp/", "respelling": "GRIP"},
  {"word": "plum", "emoji": "🍑", "chinese": "李子", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/plʌm/", "respelling": "PLUM"},
  {"word": "snap", "emoji": "📸", "chinese": "啪", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/snæp/", "respelling": "SNAP"},
  {"word": "span", "emoji": "↔️", "chinese": "跨度", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/spæn/", "respelling": "SPAN"},
  {"word": "spin", "emoji": "🌀", "chinese": "旋转", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/spɪn/", "respelling": "SPIN"},
  {"word": "spot", "emoji": "🔴", "chinese": "斑点", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/spɑːt/", "respelling": "SPAHT"},
  {"word": "step", "emoji": "👣", "chinese": "脚步", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/stɛp/", "respelling": "STEP"},
  {"word": "stem", "emoji": "🌿", "chinese": "茎", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/stɛm/", "respelling": "STEM"},
  {"word": "twig", "emoji": "🌿", "chinese": "细枝", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/twɪɡ/", "respelling": "TWIG"},
  {"word": "twin", "emoji": "👯", "chinese": "双胞胎", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/twɪn/", "respelling": "TWIN"},
  {"word": "brim", "emoji": "🎩", "chinese": "帽檐", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/brɪm/", "respelling": "BRIM"},
  {"word": "skit", "emoji": "🎭", "chinese": "短剧", "type": "phonics", "difficulty": 4, "wordType": "Blend", "gradeLevel": "1", "ipa": "/skɪt/", "respelling": "SKIT"},
  {"word": "ship", "emoji": "🚢", "chinese": "船", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ʃɪp/", "respelling": "SHIP"},
  {"word": "chip", "emoji": "🥔", "chinese": "薯片", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/tʃɪp/", "respelling": "CHIP"},
  {"word": "fish", "emoji": "🐟", "chinese": "鱼", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/fɪʃ/", "respelling": "FISH"},
  {"word": "shoe", "emoji": "👟", "chinese": "鞋", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ʃuː/", "respelling": "SHOO"},
  {"word": "chat", "emoji": "💬", "chinese": "聊天", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/tʃæt/", "respelling": "CHAT"},
  {"word": "shop", "emoji": "🛒", "chinese": "商店", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ʃɑːp/", "respelling": "SHOP"},
  {"word": "shell", "emoji": "🐚", "chinese": "贝壳", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ʃɛl/", "respelling": "SHEL"},
  {"word": "dish", "emoji": "🍽️", "chinese": "盘子", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/dɪʃ/", "respelling": "DISH"},
  {"word": "wish", "emoji": "🌠", "chinese": "愿望", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/wɪʃ/", "respelling": "WISH"},
  {"word": "chop", "emoji": "🔪", "chinese": "砍", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/tʃɑːp/", "respelling": "CHOP"},
  {"word": "chin", "emoji": "🙂", "chinese": "下巴", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/tʃɪn/", "respelling": "CHIN"},
  {"word": "math", "emoji": "➕", "chinese": "数学", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/mæθ/", "respelling": "MATH"},
  {"word": "path", "emoji": "🛤️", "chinese": "小路", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/pæθ/", "respelling": "PATH"},
  {"word": "bath", "emoji": "🛁", "chinese": "洗澡", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/bæθ/", "respelling": "BATH"},
  {"word": "moth", "emoji": "🦋", "chinese": "蛾", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/mɔːθ/", "respelling": "MAWTH"},
  {"word": "thin", "emoji": "📏", "chinese": "薄", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/θɪn/", "respelling": "THIN"},
  {"word": "that", "emoji": "👉", "chinese": "那", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ðæt/", "respelling": "THAT"},
  {"word": "then", "emoji": "⏭️", "chinese": "然后", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ðɛn/", "respelling": "THEN"},
  {"word": "white", "emoji": "⚪", "chinese": "白色", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/waɪt/", "respelling": "WYTE"},
  {"word": "whale", "emoji": "🐋", "chinese": "鲸", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/weɪl/", "respelling": "WAYL"},
  {"word": "cheek", "emoji": "😊", "chinese": "脸颊", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/tʃiːk/", "respelling": "CHEEK"},
  {"word": "chess", "emoji": "♟️", "chinese": "国际象棋", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/tʃɛs/", "respelling": "CHES"},
  {"word": "sheep", "emoji": "🐑", "chinese": "绵羊", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/ʃiːp/", "respelling": "SHEEP"},
  {"word": "thick", "emoji": "📚", "chinese": "厚的", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/θɪk/", "respelling": "THIK"},
  {"word": "thank", "emoji": "🙏", "chinese": "感谢", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/θæŋk/", "respelling": "THANK"},
  {"word": "brush", "emoji": "🖌️", "chinese": "刷子", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/brʌʃ/", "respelling": "BRUSH"},
  {"word": "lunch", "emoji": "🍱", "chinese": "午餐", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/lʌntʃ/", "respelling": "LUNCH"},
  {"word": "witch", "emoji": "🧙", "chinese": "女巫", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/wɪtʃ/", "respelling": "WITCH"},
  {"word": "peach", "emoji": "🍑", "chinese": "桃子", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/piːtʃ/", "respelling": "PEECH"},
  {"word": "bench", "emoji": "🪑", "chinese": "长凳", "type": "phonics", "difficulty": 4, "wordType": "Digraph", "gradeLevel": "1", "ipa": "/bɛntʃ/", "respelling": "BENCH"},
  {"word": "cake", "emoji": "🎂", "chinese": "蛋糕", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/keɪk/", "respelling": "KAYK"},
  {"word": "bike", "emoji": "🚲", "chinese": "自行车", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/baɪk/", "respelling": "BYKE"},
  {"word": "kite", "emoji": "🪁", "chinese": "风筝", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/kaɪt/", "respelling": "KYTE"},
  {"word": "home", "emoji": "🏠", "chinese": "家", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/hoʊm/", "respelling": "HOHM"},
  {"word": "note", "emoji": "🎵", "chinese": "音符；便条", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/noʊt/", "respelling": "NOHT"},
  {"word": "cute", "emoji": "🥰", "chinese": "可爱", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/kjuːt/", "respelling": "KYOOT"},
  {"word": "lake", "emoji": "🏞️", "chinese": "湖", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/leɪk/", "respelling": "LAYK"},
  {"word": "bake", "emoji": "🥖", "chinese": "烘烤", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/beɪk/", "respelling": "BAYK"},
  {"word": "rope", "emoji": "🪢", "chinese": "绳子", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/roʊp/", "respelling": "ROHP"},
  {"word": "hope", "emoji": "🤞", "chinese": "希望", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/hoʊp/", "respelling": "HOHP"},
  {"word": "tube", "emoji": "🧪", "chinese": "管子", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/tuːb/", "respelling": "TOOB"},
  {"word": "cube", "emoji": "🧊", "chinese": "立方体", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/kjuːb/", "respelling": "KYOOB"},
  {"word": "bone", "emoji": "🦴", "chinese": "骨头", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/boʊn/", "respelling": "BOHN"},
  {"word": "cone", "emoji": "🍦", "chinese": "甜筒", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/koʊn/", "respelling": "KOHN"},
  {"word": "dime", "emoji": "🪙", "chinese": "一角硬币", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/daɪm/", "respelling": "DYM"},
  {"word": "lime", "emoji": "🍋", "chinese": "青柠", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/laɪm/", "respelling": "LYM"},
  {"word": "ride", "emoji": "🎢", "chinese": "乘坐", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/raɪd/", "respelling": "RYDE"},
  {"word": "slide", "emoji": "🛝", "chinese": "滑梯", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/slaɪd/", "respelling": "SLYD"},
  {"word": "poke", "emoji": "👉", "chinese": "戳", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/poʊk/", "respelling": "POHK"},
  {"word": "grape", "emoji": "🍇", "chinese": "葡萄", "type": "phonics", "difficulty": 4, "wordType": "Silent e", "gradeLevel": "1", "ipa": "/ɡreɪp/", "respelling": "GRAYP"},
  {"word": "rain", "emoji": "🌧️", "chinese": "雨", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/reɪn/", "respelling": "RAYN"},
  {"word": "boat", "emoji": "⛵", "chinese": "船", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/boʊt/", "respelling": "BOHT"},
  {"word": "team", "emoji": "👥", "chinese": "队伍", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/tiːm/", "respelling": "TEEM"},
  {"word": "feet", "emoji": "🦶", "chinese": "脚（复数）", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/fiːt/", "respelling": "FEET"},
  {"word": "blue", "emoji": "🔵", "chinese": "蓝色", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/bluː/", "respelling": "BLOO"},
  {"word": "mail", "emoji": "✉️", "chinese": "邮件", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/meɪl/", "respelling": "MAYL"},
  {"word": "tail", "emoji": "🐕", "chinese": "尾巴", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/teɪl/", "respelling": "TAYL"},
  {"word": "coat", "emoji": "🧥", "chinese": "外套", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/koʊt/", "respelling": "KOHT"},
  {"word": "goat", "emoji": "🐐", "chinese": "山羊", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/ɡoʊt/", "respelling": "GOHT"},
  {"word": "soap", "emoji": "🧼", "chinese": "肥皂", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/soʊp/", "respelling": "SOHP"},
  {"word": "mean", "emoji": "😠", "chinese": "刻薄；意思是", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/miːn/", "respelling": "MEEN"},
  {"word": "bean", "emoji": "🫘", "chinese": "豆子", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/biːn/", "respelling": "BEEN"},
  {"word": "week", "emoji": "📅", "chinese": "星期", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/wiːk/", "respelling": "WEEK"},
  {"word": "peek", "emoji": "👀", "chinese": "偷看", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/piːk/", "respelling": "PEEK"},
  {"word": "train", "emoji": "🚂", "chinese": "火车", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/treɪn/", "respelling": "TRAYN"},
  {"word": "coin", "emoji": "🪙", "chinese": "硬币", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/kɔɪn/", "respelling": "KOIN"},
  {"word": "join", "emoji": "🤝", "chinese": "加入", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/dʒɔɪn/", "respelling": "JOYN"},
  {"word": "cloud", "emoji": "☁️", "chinese": "云", "type": "phonics", "difficulty": 4, "wordType": "Vowel team", "gradeLevel": "1", "ipa": "/klaʊd/", "respelling": "KLOWD"},
  {"word": "card", "emoji": "🃏", "chinese": "卡片", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/kɑːrd/", "respelling": "KARD"},
  {"word": "farm", "emoji": "🚜", "chinese": "农场", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/fɑːrm/", "respelling": "FARM"},
  {"word": "horn", "emoji": "📯", "chinese": "号角", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/hɔːrn/", "respelling": "HORN"},
  {"word": "curl", "emoji": "🌀", "chinese": "卷曲", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/kɜːrl/", "respelling": "KURL"},
  {"word": "corn", "emoji": "🌽", "chinese": "玉米", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/kɔːrn/", "respelling": "KORN"},
  {"word": "born", "emoji": "👶", "chinese": "出生", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/bɔːrn/", "respelling": "BORN"},
  {"word": "torn", "emoji": "📄", "chinese": "撕破", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/tɔːrn/", "respelling": "TORN"},
  {"word": "hard", "emoji": "💪", "chinese": "难；硬", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/hɑːrd/", "respelling": "HARD"},
  {"word": "park", "emoji": "🏞️", "chinese": "公园", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/pɑːrk/", "respelling": "PARK"},
  {"word": "mark", "emoji": "✏️", "chinese": "标记", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/mɑːrk/", "respelling": "MARK"},
  {"word": "dark", "emoji": "🌙", "chinese": "黑暗", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/dɑːrk/", "respelling": "DARK"},
  {"word": "fork", "emoji": "🍴", "chinese": "叉子", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/fɔːrk/", "respelling": "FORK"},
  {"word": "turn", "emoji": "↩️", "chinese": "转弯", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/tɜːrn/", "respelling": "TERN"},
  {"word": "burn", "emoji": "🔥", "chinese": "燃烧", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/bɜːrn/", "respelling": "BURN"},
  {"word": "surf", "emoji": "🏄", "chinese": "冲浪", "type": "phonics", "difficulty": 5, "wordType": "R-controlled", "gradeLevel": "2", "ipa": "/sɜːrf/", "respelling": "SURF"},
  {"word": "the", "emoji": "✨", "chinese": "这；那个", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ðə/", "respelling": "thuh"},
  {"word": "and", "emoji": "➕", "chinese": "和", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ænd/", "respelling": "AND"},
  {"word": "you", "emoji": "🫵", "chinese": "你", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/juː/", "respelling": "YOO"},
  {"word": "is", "emoji": "ℹ️", "chinese": "是", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɪz/", "respelling": "IZ"},
  {"word": "it", "emoji": "📌", "chinese": "它", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɪt/", "respelling": "IT"},
  {"word": "in", "emoji": "📥", "chinese": "在…里", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɪn/", "respelling": "IN"},
  {"word": "on", "emoji": "📍", "chinese": "在…上", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɑːn/", "respelling": "ON"},
  {"word": "to", "emoji": "➡️", "chinese": "向；到", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/tuː/", "respelling": "TOO"},
  {"word": "we", "emoji": "🧑‍🤝‍🧑", "chinese": "我们", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/wiː/", "respelling": "WEE"},
  {"word": "go", "emoji": "🚶", "chinese": "去", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɡoʊ/", "respelling": "GOH"},
  {"word": "me", "emoji": "🙋", "chinese": "我", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/miː/", "respelling": "MEE"},
  {"word": "a", "emoji": "🔤", "chinese": "一个（冠词）", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ə/", "respelling": "uh"},
  {"word": "see", "emoji": "👀", "chinese": "看见", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/siː/", "respelling": "SEE"},
  {"word": "my", "emoji": "🧒", "chinese": "我的", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/maɪ/", "respelling": "MY"},
  {"word": "can", "emoji": "💪", "chinese": "能", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/kæn/", "respelling": "KAN"},
  {"word": "look", "emoji": "👀", "chinese": "看", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/lʊk/", "respelling": "LOOK"},
  {"word": "like", "emoji": "👍", "chinese": "喜欢", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/laɪk/", "respelling": "LYKE"},
  {"word": "here", "emoji": "📍", "chinese": "这里", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/hɪər/", "respelling": "HEER"},
  {"word": "come", "emoji": "🚶‍➡️", "chinese": "来", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/kʌm/", "respelling": "KUM"},
  {"word": "one", "emoji": "1️⃣", "chinese": "一", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/wʌn/", "respelling": "WUN"},
  {"word": "two", "emoji": "2️⃣", "chinese": "二", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/tuː/", "respelling": "TOO"},
  {"word": "three", "emoji": "3️⃣", "chinese": "三", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/θriː/", "respelling": "THREE"},
  {"word": "up", "emoji": "⬆️", "chinese": "上", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ʌp/", "respelling": "UP"},
  {"word": "down", "emoji": "⬇️", "chinese": "下", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/daʊn/", "respelling": "DOWN"},
  {"word": "yes", "emoji": "✅", "chinese": "是", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/jɛs/", "respelling": "YES"},
  {"word": "no", "emoji": "❎", "chinese": "不", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/noʊ/", "respelling": "NOH"},
  {"word": "help", "emoji": "🆘", "chinese": "帮助", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/hɛlp/", "respelling": "HELP"},
  {"word": "jump", "emoji": "🦘", "chinese": "跳", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/dʒʌmp/", "respelling": "JUMP"},
  {"word": "he", "emoji": "👦", "chinese": "他", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/hiː/", "respelling": "HEE"},
  {"word": "his", "emoji": "🏷️", "chinese": "他的", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/hɪz/", "respelling": "HIZ"},
  {"word": "her", "emoji": "👧", "chinese": "她；她的", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/hɜːr/", "respelling": "HUR"},
  {"word": "at", "emoji": "🎯", "chinese": "在", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/æt/", "respelling": "AT"},
  {"word": "for", "emoji": "🎁", "chinese": "为了", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/fɔːr/", "respelling": "FOR"},
  {"word": "get", "emoji": "🤲", "chinese": "得到", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɡɛt/", "respelling": "GET"},
  {"word": "not", "emoji": "🚫", "chinese": "不", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/nɑːt/", "respelling": "NOT"},
  {"word": "so", "emoji": "✨", "chinese": "所以；很", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/soʊ/", "respelling": "SOH"},
  {"word": "day", "emoji": "🌤️", "chinese": "天；日子", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/deɪ/", "respelling": "DAY"},
  {"word": "want", "emoji": "🙏", "chinese": "想要", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/wɑːnt/", "respelling": "WAHNT"},
  {"word": "this", "emoji": "👆", "chinese": "这个", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ðɪs/", "respelling": "THIS"},
  {"word": "good", "emoji": "👍", "chinese": "好", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɡʊd/", "respelling": "GOOD"},
  {"word": "all", "emoji": "🔁", "chinese": "全部", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ɔːl/", "respelling": "AWL"},
  {"word": "out", "emoji": "🚪", "chinese": "外；出", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/aʊt/", "respelling": "OUT"},
  {"word": "make", "emoji": "🛠️", "chinese": "做", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/meɪk/", "respelling": "MAYK"},
  {"word": "say", "emoji": "💬", "chinese": "说", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/seɪ/", "respelling": "SAY"},
  {"word": "your", "emoji": "👉", "chinese": "你的", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/jʊər/", "respelling": "YOOR"},
  {"word": "funny", "emoji": "😂", "chinese": "好笑", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ˈfʌni/", "respelling": "FUN-ee"},
  {"word": "little", "emoji": "🤏", "chinese": "小", "type": "sight", "difficulty": 2, "wordType": "Heart word", "gradeLevel": "K", "ipa": "/ˈlɪtəl/", "respelling": "LIT-ul"},
  {"word": "they", "emoji": "👥", "chinese": "他们", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/ðeɪ/", "respelling": "THAY"},
  {"word": "have", "emoji": "📦", "chinese": "有", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/hæv/", "respelling": "HAV"},
  {"word": "said", "emoji": "💬", "chinese": "说", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/sɛd/", "respelling": "SED"},
  {"word": "from", "emoji": "📤", "chinese": "从", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/frʌm/", "respelling": "FRUM"},
  {"word": "what", "emoji": "❓", "chinese": "什么", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/wʌt/", "respelling": "WUT"},
  {"word": "when", "emoji": "🕐", "chinese": "何时", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/wɛn/", "respelling": "WEN"},
  {"word": "where", "emoji": "🧭", "chinese": "哪里", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/wer/", "respelling": "WAIR"},
  {"word": "why", "emoji": "🤔", "chinese": "为什么", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/waɪ/", "respelling": "WY"},
  {"word": "how", "emoji": "❔", "chinese": "怎样", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/haʊ/", "respelling": "HOW"},
  {"word": "could", "emoji": "🔮", "chinese": "能", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/kʊd/", "respelling": "KOOD"},
  {"word": "was", "emoji": "⏪", "chinese": "是", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/wʌz/", "respelling": "WUZ"},
  {"word": "are", "emoji": "↔️", "chinese": "是", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/ɑːr/", "respelling": "AR"},
  {"word": "now", "emoji": "📍", "chinese": "现在", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/naʊ/", "respelling": "NOW"},
  {"word": "she", "emoji": "👩", "chinese": "她", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/ʃiː/", "respelling": "SHE"},
  {"word": "some", "emoji": "🤲", "chinese": "一些", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/sʌm/", "respelling": "SUM"},
  {"word": "there", "emoji": "👉", "chinese": "那里", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/ðɛr/", "respelling": "THAIR"},
  {"word": "an", "emoji": "📝", "chinese": "一个", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/æn/", "respelling": "AN"},
  {"word": "him", "emoji": "👦", "chinese": "他（宾格）", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/hɪm/", "respelling": "HIM"},
  {"word": "has", "emoji": "📦", "chinese": "有（三单）", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/hæz/", "respelling": "HAZ"},
  {"word": "had", "emoji": "📜", "chinese": "有过", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/hæd/", "respelling": "HAD"},
  {"word": "were", "emoji": "👥", "chinese": "是（are 的过去）", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/wɜːr/", "respelling": "WUR"},
  {"word": "into", "emoji": "📥", "chinese": "进入", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/ˈɪntuː/", "respelling": "IN-too"},
  {"word": "off", "emoji": "⏹️", "chinese": "离开；关掉", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/ɔːf/", "respelling": "AWF"},
  {"word": "our", "emoji": "🧑‍🤝‍🧑", "chinese": "我们的", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/aʊər/", "respelling": "OW-er"},
  {"word": "ask", "emoji": "🙋", "chinese": "问", "type": "sight", "difficulty": 3, "wordType": "Heart word", "gradeLevel": "1", "ipa": "/æsk/", "respelling": "ASK"},
  {"word": "always", "emoji": "♾️", "chinese": "总是", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/ˈɔːlweɪz/", "respelling": "AWL-wayz"},
  {"word": "before", "emoji": "⏮️", "chinese": "在…之前", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/bɪˈfɔːr/", "respelling": "bee-FOR"},
  {"word": "found", "emoji": "🔍", "chinese": "找到", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/faʊnd/", "respelling": "FOWND"},
  {"word": "green", "emoji": "🟢", "chinese": "绿色", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/ɡriːn/", "respelling": "GREEN"},
  {"word": "know", "emoji": "🧠", "chinese": "知道", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/noʊ/", "respelling": "NOH"},
  {"word": "laugh", "emoji": "😂", "chinese": "笑", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/læf/", "respelling": "LAF"},
  {"word": "read", "emoji": "📖", "chinese": "读", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/riːd/", "respelling": "REED"},
  {"word": "right", "emoji": "✅", "chinese": "对；右边", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/raɪt/", "respelling": "RYTE"},
  {"word": "sleep", "emoji": "😴", "chinese": "睡觉", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/sliːp/", "respelling": "SLEEP"},
  {"word": "tell", "emoji": "🗣️", "chinese": "告诉", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/tɛl/", "respelling": "TEL"},
  {"word": "their", "emoji": "👥", "chinese": "他们的", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/ðɛr/", "respelling": "THAIR"},
  {"word": "very", "emoji": "⭐", "chinese": "非常", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/ˈvɛri/", "respelling": "VER-ee"},
  {"word": "wash", "emoji": "🧼", "chinese": "洗", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/wɑːʃ/", "respelling": "WAHSH"},
  {"word": "which", "emoji": "❓", "chinese": "哪一个", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/wɪtʃ/", "respelling": "WITCH"},
  {"word": "would", "emoji": "💭", "chinese": "会；愿意", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/wʊd/", "respelling": "WOOD"},
  {"word": "around", "emoji": "🔄", "chinese": "周围", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/əˈraʊnd/", "respelling": "uh-ROWND"},
  {"word": "because", "emoji": "💡", "chinese": "因为", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/bɪˈkɔːz/", "respelling": "bee-KAWZ"},
  {"word": "best", "emoji": "🏆", "chinese": "最好", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/bɛst/", "respelling": "BEST"},
  {"word": "buy", "emoji": "🛒", "chinese": "买", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/baɪ/", "respelling": "BY"},
  {"word": "cold", "emoji": "🥶", "chinese": "冷", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/koʊld/", "respelling": "KOHLD"},
  {"word": "does", "emoji": "❓", "chinese": "做（三单）", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/dʌz/", "respelling": "DUZ"},
  {"word": "fast", "emoji": "⚡", "chinese": "快", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/fæst/", "respelling": "FAST"},
  {"word": "first", "emoji": "1️⃣", "chinese": "第一", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/fɜːrst/", "respelling": "FURST"},
  {"word": "five", "emoji": "5️⃣", "chinese": "五", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/faɪv/", "respelling": "FYVE"},
  {"word": "give", "emoji": "🎁", "chinese": "给", "type": "sight", "difficulty": 4, "wordType": "Heart word", "gradeLevel": "2", "ipa": "/ɡɪv/", "respelling": "GIV"},
  {"word": "apple", "emoji": "🍎", "chinese": "苹果", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/ˈæpəl/", "respelling": "AP-ul"},
  {"word": "banana", "emoji": "🍌", "chinese": "香蕉", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/bəˈnænə/", "respelling": "buh-NAN-uh"},
  {"word": "ball", "emoji": "⚽", "chinese": "球", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/bɔːl/", "respelling": "BAWL"},
  {"word": "tree", "emoji": "🌳", "chinese": "树", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/triː/", "respelling": "TREE"},
  {"word": "bird", "emoji": "🐦", "chinese": "鸟", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/bɜːrd/", "respelling": "BURD"},
  {"word": "water", "emoji": "💧", "chinese": "水", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/ˈwɔːtər/", "respelling": "WAW-ter"},
  {"word": "milk", "emoji": "🥛", "chinese": "牛奶", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/mɪlk/", "respelling": "MILK"},
  {"word": "book", "emoji": "📚", "chinese": "书", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/bʊk/", "respelling": "BOOK"},
  {"word": "door", "emoji": "🚪", "chinese": "门", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/dɔːr/", "respelling": "DOR"},
  {"word": "house", "emoji": "🏠", "chinese": "房子", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/haʊs/", "respelling": "HOWSS"},
  {"word": "school", "emoji": "🏫", "chinese": "学校", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/skuːl/", "respelling": "SKOOL"},
  {"word": "teacher", "emoji": "👩‍🏫", "chinese": "老师", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/ˈtiːtʃər/", "respelling": "TEE-chur"},
  {"word": "friend", "emoji": "🤝", "chinese": "朋友", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/frɛnd/", "respelling": "FREND"},
  {"word": "family", "emoji": "👪", "chinese": "家庭", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/ˈfæməli/", "respelling": "FAM-uh-lee"},
  {"word": "play", "emoji": "🎮", "chinese": "玩", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/pleɪ/", "respelling": "PLAY"},
  {"word": "pink", "emoji": "🩷", "chinese": "粉色", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/pɪŋk/", "respelling": "PINK"},
  {"word": "brown", "emoji": "🟤", "chinese": "棕色", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/braʊn/", "respelling": "BROWN"},
  {"word": "yellow", "emoji": "🟡", "chinese": "黄色", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/ˈjɛloʊ/", "respelling": "YEL-oh"},
  {"word": "four", "emoji": "4️⃣", "chinese": "四", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/fɔːr/", "respelling": "FOR"},
  {"word": "seven", "emoji": "7️⃣", "chinese": "七", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/ˈsɛvən/", "respelling": "SEV-en"},
  {"word": "eight", "emoji": "8️⃣", "chinese": "八", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/eɪt/", "respelling": "AYT"},
  {"word": "nine", "emoji": "9️⃣", "chinese": "九", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/naɪn/", "respelling": "NYN"},
  {"word": "zero", "emoji": "0️⃣", "chinese": "零", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/ˈzɪroʊ/", "respelling": "ZEER-oh"},
  {"word": "bear", "emoji": "🐻", "chinese": "熊", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/ber/", "respelling": "BAIR"},
  {"word": "duck", "emoji": "🦆", "chinese": "鸭子", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/dʌk/", "respelling": "DUK"},
  {"word": "horse", "emoji": "🐴", "chinese": "马", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/hɔːrs/", "respelling": "HORSS"},
  {"word": "cow", "emoji": "🐄", "chinese": "牛", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/kaʊ/", "respelling": "KOW"},
  {"word": "bee", "emoji": "🐝", "chinese": "蜜蜂", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/biː/", "respelling": "BEE"},
  {"word": "bread", "emoji": "🍞", "chinese": "面包", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/brɛd/", "respelling": "BRED"},
  {"word": "rice", "emoji": "🍚", "chinese": "米饭", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/raɪs/", "respelling": "RYSS"},
  {"word": "egg", "emoji": "🥚", "chinese": "鸡蛋", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/ɛɡ/", "respelling": "EG"},
  {"word": "pizza", "emoji": "🍕", "chinese": "披萨", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/ˈpiːtsə/", "respelling": "PEET-suh"},
  {"word": "soup", "emoji": "🍲", "chinese": "汤", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/suːp/", "respelling": "SOOP"},
  {"word": "head", "emoji": "🗣️", "chinese": "头", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/hɛd/", "respelling": "HED"},
  {"word": "hand", "emoji": "✋", "chinese": "手", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/hænd/", "respelling": "HAND"},
  {"word": "foot", "emoji": "🦶", "chinese": "脚", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/fʊt/", "respelling": "FOOT"},
  {"word": "eye", "emoji": "👁️", "chinese": "眼睛", "type": "basic", "difficulty": 2, "wordType": "Basic", "gradeLevel": "K", "ipa": "/aɪ/", "respelling": "EYE"},
  {"word": "spring", "emoji": "🌸", "chinese": "春天", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/sprɪŋ/", "respelling": "SPRING"},
  {"word": "summer", "emoji": "☀️", "chinese": "夏天", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/ˈsʌmər/", "respelling": "SUM-er"},
  {"word": "winter", "emoji": "❄️", "chinese": "冬天", "type": "basic", "difficulty": 3, "wordType": "Basic", "gradeLevel": "1", "ipa": "/ˈwɪntər/", "respelling": "WIN-ter"},
  {"word": "about", "emoji": "💬", "chinese": "关于", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/əˈbaʊt/", "respelling": "uh-BOWT"},
  {"word": "better", "emoji": "⬆️", "chinese": "更好", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ˈbɛtər/", "respelling": "BET-er"},
  {"word": "carry", "emoji": "🎒", "chinese": "携带", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ˈkæri/", "respelling": "KAR-ee"},
  {"word": "clean", "emoji": "🧹", "chinese": "干净", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/kliːn/", "respelling": "KLEEN"},
  {"word": "earth", "emoji": "🌍", "chinese": "地球", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ɜːrθ/", "respelling": "URTH"},
  {"word": "fall", "emoji": "🍂", "chinese": "落下；秋天", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/fɔːl/", "respelling": "FAWL"},
  {"word": "full", "emoji": "🫙", "chinese": "满的", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/fʊl/", "respelling": "FUL"},
  {"word": "hold", "emoji": "🤲", "chinese": "握住", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/hoʊld/", "respelling": "HOHLD"},
  {"word": "hurt", "emoji": "🤕", "chinese": "受伤", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/hɜːrt/", "respelling": "HURT"},
  {"word": "keep", "emoji": "🔒", "chinese": "保持", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/kiːp/", "respelling": "KEEP"},
  {"word": "kind", "emoji": "💗", "chinese": "友善", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/kaɪnd/", "respelling": "KYND"},
  {"word": "long", "emoji": "📏", "chinese": "长", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/lɔːŋ/", "respelling": "LAWNG"},
  {"word": "much", "emoji": "📦", "chinese": "许多", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/mʌtʃ/", "respelling": "MUCH"},
  {"word": "never", "emoji": "🚫", "chinese": "从不", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ˈnɛvər/", "respelling": "NEV-er"},
  {"word": "only", "emoji": "1️⃣", "chinese": "只有", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ˈoʊnli/", "respelling": "OHN-lee"},
  {"word": "own", "emoji": "🏠", "chinese": "自己的", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/oʊn/", "respelling": "OHN"},
  {"word": "pick", "emoji": "🌸", "chinese": "挑选", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/pɪk/", "respelling": "PIK"},
  {"word": "shall", "emoji": "📜", "chinese": "将要", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ʃæl/", "respelling": "SHAL"},
  {"word": "show", "emoji": "👀", "chinese": "展示", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ʃoʊ/", "respelling": "SHOH"},
  {"word": "start", "emoji": "🏁", "chinese": "开始", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/stɑːrt/", "respelling": "START"},
  {"word": "today", "emoji": "📅", "chinese": "今天", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/təˈdeɪ/", "respelling": "tuh-DAY"},
  {"word": "together", "emoji": "🤝", "chinese": "一起", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/təˈɡɛðər/", "respelling": "tuh-GETH-er"},
  {"word": "try", "emoji": "💪", "chinese": "尝试", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/traɪ/", "respelling": "TRY"},
  {"word": "warm", "emoji": "☀️", "chinese": "温暖", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/wɔːrm/", "respelling": "WARM"},
  {"word": "also", "emoji": "➕", "chinese": "也", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ˈɔːlsoʊ/", "respelling": "AWL-soh"},
  {"word": "answer", "emoji": "✅", "chinese": "答案", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ˈænsər/", "respelling": "AN-ser"},
  {"word": "city", "emoji": "🏙️", "chinese": "城市", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ˈsɪti/", "respelling": "SIT-ee"},
  {"word": "famous", "emoji": "⭐", "chinese": "著名", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ˈfeɪməs/", "respelling": "FAY-mus"},
  {"word": "group", "emoji": "👥", "chinese": "小组", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ɡruːp/", "respelling": "GROOP"},
  {"word": "listen", "emoji": "👂", "chinese": "听", "type": "sight", "difficulty": 5, "wordType": "Heart word", "gradeLevel": "3", "ipa": "/ˈlɪsən/", "respelling": "LIS-en"},
  {"word": "measure", "emoji": "📏", "chinese": "测量", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈmɛʒər/", "respelling": "MEZH-er"},
  {"word": "question", "emoji": "❓", "chinese": "问题", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈkwɛstʃən/", "respelling": "KWES-chun"},
  {"word": "special", "emoji": "✨", "chinese": "特别", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈspɛʃəl/", "respelling": "SPESH-ul"},
  {"word": "surprise", "emoji": "🎁", "chinese": "惊喜", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/sərˈpraɪz/", "respelling": "ser-PRYZ"},
  {"word": "though", "emoji": "🤔", "chinese": "虽然", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ðoʊ/", "respelling": "THOH"},
  {"word": "young", "emoji": "🧒", "chinese": "年轻", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/jʌŋ/", "respelling": "YUNG"},
  {"word": "among", "emoji": "👥", "chinese": "在…之中", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/əˈmʌŋ/", "respelling": "uh-MUNG"},
  {"word": "caught", "emoji": "🎣", "chinese": "抓住", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/kɔːt/", "respelling": "KAWT"},
  {"word": "country", "emoji": "🗺️", "chinese": "国家", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈkʌntri/", "respelling": "KUN-tree"},
  {"word": "early", "emoji": "🌅", "chinese": "早", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈɜːrli/", "respelling": "UR-lee"},
  {"word": "example", "emoji": "💡", "chinese": "例子", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ɪɡˈzæmpəl/", "respelling": "ig-ZAM-pul"},
  {"word": "field", "emoji": "🌾", "chinese": "田野", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/fiːld/", "respelling": "FEELD"},
  {"word": "forest", "emoji": "🌲", "chinese": "森林", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈfɔːrɪst/", "respelling": "FOR-ist"},
  {"word": "history", "emoji": "📜", "chinese": "历史", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈhɪstəri/", "respelling": "HIS-tuh-ree"},
  {"word": "island", "emoji": "🏝️", "chinese": "岛屿", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈaɪlənd/", "respelling": "EYE-lund"},
  {"word": "language", "emoji": "🗣️", "chinese": "语言", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈlæŋɡwɪdʒ/", "respelling": "LANG-gwij"},
  {"word": "notice", "emoji": "👀", "chinese": "注意到", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈnoʊtɪs/", "respelling": "NOH-tis"},
  {"word": "object", "emoji": "📦", "chinese": "物体", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈɑːbdʒɛkt/", "respelling": "AHB-jekt"},
  {"word": "paragraph", "emoji": "📄", "chinese": "段落", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈpærəɡræf/", "respelling": "PAR-uh-graf"},
  {"word": "passage", "emoji": "📖", "chinese": "段落；通道", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈpæsɪdʒ/", "respelling": "PAS-ij"},
  {"word": "planet", "emoji": "🪐", "chinese": "行星", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈplænɪt/", "respelling": "PLAN-it"},
  {"word": "problem", "emoji": "🧩", "chinese": "问题", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈprɑːbləm/", "respelling": "PRAH-blum"},
  {"word": "region", "emoji": "🗺️", "chinese": "地区", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈriːdʒən/", "respelling": "REE-jun"},
  {"word": "remember", "emoji": "🧠", "chinese": "记得", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/rɪˈmɛmbər/", "respelling": "ri-MEM-ber"},
  {"word": "science", "emoji": "🔬", "chinese": "科学", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈsaɪəns/", "respelling": "SY-ens"},
  {"word": "sentence", "emoji": "📝", "chinese": "句子", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈsɛntəns/", "respelling": "SEN-tens"},
  {"word": "suppose", "emoji": "💭", "chinese": "猜想", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/səˈpoʊz/", "respelling": "suh-POHZ"},
  {"word": "therefore", "emoji": "➡️", "chinese": "因此", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈðɛrfɔːr/", "respelling": "THAIR-for"},
  {"word": "vegetable", "emoji": "🥕", "chinese": "蔬菜", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈvɛdʒtəbəl/", "respelling": "VEJ-tuh-bul"},
  {"word": "whether", "emoji": "🤷", "chinese": "是否", "type": "sight", "difficulty": 6, "wordType": "Heart word", "gradeLevel": "4", "ipa": "/ˈwɛðər/", "respelling": "WETH-er"},
  {"word": "animal", "emoji": "🐾", "chinese": "动物", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈænɪməl/", "respelling": "AN-uh-mul"},
  {"word": "basket", "emoji": "🧺", "chinese": "篮子", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈbæskɪt/", "respelling": "BAS-kit"},
  {"word": "candle", "emoji": "🕯️", "chinese": "蜡烛", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈkændəl/", "respelling": "KAN-dul"},
  {"word": "carrot", "emoji": "🥕", "chinese": "胡萝卜", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈkærət/", "respelling": "KAR-ut"},
  {"word": "dinner", "emoji": "🍽️", "chinese": "晚餐", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈdɪnər/", "respelling": "DIN-er"},
  {"word": "finger", "emoji": "☝️", "chinese": "手指", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈfɪŋɡər/", "respelling": "FING-er"},
  {"word": "happy", "emoji": "😊", "chinese": "快乐", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈhæpi/", "respelling": "HAP-ee"},
  {"word": "kitten", "emoji": "🐱", "chinese": "小猫", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈkɪtən/", "respelling": "KIT-en"},
  {"word": "lemon", "emoji": "🍋", "chinese": "柠檬", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈlɛmən/", "respelling": "LEM-un"},
  {"word": "magic", "emoji": "✨", "chinese": "魔法", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈmædʒɪk/", "respelling": "MAJ-ik"},
  {"word": "monkey", "emoji": "🐒", "chinese": "猴子", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈmʌŋki/", "respelling": "MUNG-kee"},
  {"word": "number", "emoji": "🔢", "chinese": "数字", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈnʌmbər/", "respelling": "NUM-ber"},
  {"word": "pencil", "emoji": "✏️", "chinese": "铅笔", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈpɛnsəl/", "respelling": "PEN-sul"},
  {"word": "pocket", "emoji": "👖", "chinese": "口袋", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈpɑːkɪt/", "respelling": "PAH-kit"},
  {"word": "pumpkin", "emoji": "🎃", "chinese": "南瓜", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈpʌmpkɪn/", "respelling": "PUMP-kin"},
  {"word": "rabbit", "emoji": "🐰", "chinese": "兔子", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈræbɪt/", "respelling": "RAB-it"},
  {"word": "rocket", "emoji": "🚀", "chinese": "火箭", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈrɑːkɪt/", "respelling": "RAH-kit"},
  {"word": "silver", "emoji": "🥈", "chinese": "银色", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈsɪlvər/", "respelling": "SIL-ver"},
  {"word": "trumpet", "emoji": "🎺", "chinese": "小号", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈtrʌmpɪt/", "respelling": "TRUMP-it"},
  {"word": "window", "emoji": "🪟", "chinese": "窗户", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈwɪndoʊ/", "respelling": "WIN-doh"},
  {"word": "blanket", "emoji": "🛏️", "chinese": "毯子", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈblæŋkɪt/", "respelling": "BLANG-kit"},
  {"word": "golden", "emoji": "🏅", "chinese": "金色", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈɡoʊldən/", "respelling": "GOHL-den"},
  {"word": "happen", "emoji": "⚡", "chinese": "发生", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈhæpən/", "respelling": "HAP-un"},
  {"word": "jacket", "emoji": "🧥", "chinese": "夹克", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈdʒækɪt/", "respelling": "JAK-it"},
  {"word": "lesson", "emoji": "📚", "chinese": "课", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈlɛsən/", "respelling": "LES-un"},
  {"word": "market", "emoji": "🏪", "chinese": "市场", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈmɑːrkɪt/", "respelling": "MAR-kit"},
  {"word": "napkin", "emoji": "🧻", "chinese": "餐巾", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈnæpkɪn/", "respelling": "NAP-kin"},
  {"word": "picnic", "emoji": "🧺", "chinese": "野餐", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈpɪknɪk/", "respelling": "PIK-nik"},
  {"word": "ticket", "emoji": "🎫", "chinese": "票", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈtɪkɪt/", "respelling": "TIK-it"},
  {"word": "travel", "emoji": "✈️", "chinese": "旅行", "type": "phonics", "difficulty": 5, "wordType": "Multisyllable", "gradeLevel": "3", "ipa": "/ˈtrævəl/", "respelling": "TRAV-ul"},
  {"word": "preview", "emoji": "👀", "chinese": "预览", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈpriːvjuː/", "respelling": "PREE-vyoo"},
  {"word": "reread", "emoji": "📖", "chinese": "重读", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/riːˈriːd/", "respelling": "ree-REED"},
  {"word": "subway", "emoji": "🚇", "chinese": "地铁", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈsʌbweɪ/", "respelling": "SUB-way"},
  {"word": "unhappy", "emoji": "😢", "chinese": "不开心", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ʌnˈhæpi/", "respelling": "un-HAP-ee"},
  {"word": "refill", "emoji": "🔄", "chinese": "再装满", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/riːˈfɪl/", "respelling": "ree-FIL"},
  {"word": "rewrite", "emoji": "✍️", "chinese": "重写", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/riːˈraɪt/", "respelling": "ree-RYTE"},
  {"word": "hopeful", "emoji": "🌈", "chinese": "有希望", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈhoʊpfəl/", "respelling": "HOHP-ful"},
  {"word": "joyful", "emoji": "😄", "chinese": "快乐", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈdʒɔɪfəl/", "respelling": "JOY-ful"},
  {"word": "quickly", "emoji": "⚡", "chinese": "快速地", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈkwɪkli/", "respelling": "KWIK-lee"},
  {"word": "slowly", "emoji": "🐢", "chinese": "慢慢地", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈsloʊli/", "respelling": "SLOH-lee"},
  {"word": "baking", "emoji": "🥧", "chinese": "烘焙", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈbeɪkɪŋ/", "respelling": "BAY-king"},
  {"word": "running", "emoji": "🏃", "chinese": "跑步", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈrʌnɪŋ/", "respelling": "RUN-ing"},
  {"word": "jumped", "emoji": "🦘", "chinese": "跳了", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/dʒʌmpt/", "respelling": "JUMPT"},
  {"word": "playing", "emoji": "🎮", "chinese": "玩耍", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈpleɪɪŋ/", "respelling": "PLAY-ing"},
  {"word": "kindness", "emoji": "💗", "chinese": "善良", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈkaɪndnəs/", "respelling": "KYND-nis"},
  {"word": "darkness", "emoji": "🌑", "chinese": "黑暗", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈdɑːrknəs/", "respelling": "DARK-nis"},
  {"word": "helpful", "emoji": "🤝", "chinese": "有帮助", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈhɛlpfəl/", "respelling": "HELP-ful"},
  {"word": "careful", "emoji": "⚠️", "chinese": "小心", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈkerfəl/", "respelling": "KAIR-ful"},
  {"word": "fearless", "emoji": "🦁", "chinese": "无畏", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈfɪrləs/", "respelling": "FEER-lis"},
  {"word": "powerful", "emoji": "💪", "chinese": "强大", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈpaʊərfəl/", "respelling": "POW-er-ful"},
  {"word": "weakness", "emoji": "🪶", "chinese": "弱点", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈwiːknəs/", "respelling": "WEEK-nis"},
  {"word": "movement", "emoji": "💃", "chinese": "运动", "type": "phonics", "difficulty": 6, "wordType": "Prefix & suffix", "gradeLevel": "4", "ipa": "/ˈmuːvmənt/", "respelling": "MOOV-munt"},
  {"word": "ocean", "emoji": "🌊", "chinese": "海洋", "type": "basic", "difficulty": 5, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈoʊʃən/", "respelling": "OH-shun"},
  {"word": "mountain", "emoji": "⛰️", "chinese": "山", "type": "basic", "difficulty": 5, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈmaʊntən/", "respelling": "MOWN-tin"},
  {"word": "desert", "emoji": "🏜️", "chinese": "沙漠", "type": "basic", "difficulty": 5, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈdɛzərt/", "respelling": "DEZ-ert"},
  {"word": "hurricane", "emoji": "🌀", "chinese": "飓风", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈhɜːrəkeɪn/", "respelling": "HUR-uh-kayn"},
  {"word": "dinosaur", "emoji": "🦕", "chinese": "恐龙", "type": "basic", "difficulty": 5, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈdaɪnəsɔːr/", "respelling": "DY-nuh-sor"},
  {"word": "cafeteria", "emoji": "🍽️", "chinese": "食堂", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˌkæfəˈtɪriə/", "respelling": "kaf-uh-TIR-ee-uh"},
  {"word": "museum", "emoji": "🏛️", "chinese": "博物馆", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "3", "ipa": "/mjuˈziːəm/", "respelling": "myoo-ZEE-um"},
  {"word": "hospital", "emoji": "🏥", "chinese": "医院", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈhɑːspɪtl/", "respelling": "HAHS-pih-tul"},
  {"word": "rectangle", "emoji": "▭", "chinese": "长方形", "type": "basic", "difficulty": 5, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈrɛktæŋɡəl/", "respelling": "REK-tang-gul"},
  {"word": "triangle", "emoji": "🔺", "chinese": "三角形", "type": "basic", "difficulty": 5, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈtraɪæŋɡəl/", "respelling": "TRY-ang-gul"},
  {"word": "alphabet", "emoji": "🔤", "chinese": "字母表", "type": "basic", "difficulty": 5, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈælfəbɛt/", "respelling": "AL-fuh-bet"},
  {"word": "dictionary", "emoji": "📕", "chinese": "词典", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈdɪkʃəneri/", "respelling": "DIK-shuh-ner-ee"},
  {"word": "autumn", "emoji": "🍁", "chinese": "秋天", "type": "basic", "difficulty": 5, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈɔːtəm/", "respelling": "AW-tum"},
  {"word": "calendar", "emoji": "📆", "chinese": "日历", "type": "basic", "difficulty": 5, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈkæləndər/", "respelling": "KAL-un-der"},
  {"word": "compass", "emoji": "🧭", "chinese": "指南针", "type": "basic", "difficulty": 5, "wordType": "Basic", "gradeLevel": "3", "ipa": "/ˈkʌmpəs/", "respelling": "KUM-pus"},
  {"word": "volcano", "emoji": "🌋", "chinese": "火山", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/vɑːlˈkeɪnoʊ/", "respelling": "vahl-KAY-noh"},
  {"word": "tornado", "emoji": "🌪️", "chinese": "龙卷风", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/tɔːrˈneɪdoʊ/", "respelling": "tor-NAY-doh"},
  {"word": "galaxy", "emoji": "🌌", "chinese": "星系", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/ˈɡæləksi/", "respelling": "GAL-uk-see"},
  {"word": "microscope", "emoji": "🔬", "chinese": "显微镜", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/ˈmaɪkrəskoʊp/", "respelling": "MY-kruh-skohp"},
  {"word": "telescope", "emoji": "🔭", "chinese": "望远镜", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/ˈtɛləskoʊp/", "respelling": "TEL-uh-skohp"},
  {"word": "encyclopedia", "emoji": "📚", "chinese": "百科全书", "type": "basic", "difficulty": 7, "wordType": "Basic", "gradeLevel": "4", "ipa": "/ɪnˌsaɪkləˈpiːdiə/", "respelling": "in-SY-kluh-PEE-dee-uh"},
  {"word": "peninsula", "emoji": "🏖️", "chinese": "半岛", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/pəˈnɪnsələ/", "respelling": "puh-NIN-suh-luh"},
  {"word": "equator", "emoji": "🌍", "chinese": "赤道", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/ɪˈkweɪtər/", "respelling": "ih-KWAY-ter"},
  {"word": "geography", "emoji": "🗺️", "chinese": "地理", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/dʒiˈɑːɡrəfi/", "respelling": "jee-AH-gruh-fee"},
  {"word": "civilization", "emoji": "🏛️", "chinese": "文明", "type": "basic", "difficulty": 7, "wordType": "Basic", "gradeLevel": "4", "ipa": "/ˌsɪvələˈzeɪʃən/", "respelling": "siv-uh-luh-ZAY-shun"},
  {"word": "electricity", "emoji": "⚡", "chinese": "电", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/ɪˌlɛkˈtrɪsɪti/", "respelling": "ih-lek-TRIS-ih-tee"},
  {"word": "temperature", "emoji": "🌡️", "chinese": "温度", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/ˈtɛmpərətʃər/", "respelling": "TEMP-er-uh-chur"},
  {"word": "experiment", "emoji": "🧪", "chinese": "实验", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/ɪkˈspɛrəmənt/", "respelling": "ik-SPER-uh-munt"},
  {"word": "multiplication", "emoji": "✖️", "chinese": "乘法", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/ˌmʌltəplɪˈkeɪʃən/", "respelling": "mul-tuh-pli-KAY-shun"},
  {"word": "division", "emoji": "➗", "chinese": "除法", "type": "basic", "difficulty": 6, "wordType": "Basic", "gradeLevel": "4", "ipa": "/dɪˈvɪʒən/", "respelling": "di-VIJ-un"}
]
